### ISSUE TITLE
how to roll back from PoS to PoA?

### ISSUE THREAD

**Issue by ghost** [0xPolygon/polygon-edge#1213]
In light of the SEC dealing yet another blow to crypto currency, this time in the form of staking, we would like to roll back to PoA. Can this be done with a live chain? Is it as simple as specifying a migration block height from PoS to PoA?

We are on Ubuntu 20.04. All cloud based. V0.6.1

@laviniat1996 , can you help please?

Thanks, Nex

**Comment by laviniat1996** [comment]
@Nexsuperne101 The switch is similar to the one for PoS:
`polygon-edge ibft switch --chain ./genesis.json  --ibft-validators-prefix-path test-chain- --type PoA --from 350`
Just an example. You modify this accordingly. 

(If you are using ECDSA, you need to add an extra flag `--ibft-validator-type ecdsa `)

**Comment by ghost** [comment]
@laviniat1996 Thanks for your prompt reply. I take it that because we are a live cloud based chain, we can omit the --ibft-validators-prefix-path test-chain- flag and just use this exact line (with our required block height)?

polygon-edge ibft switch --chain ./genesis.json --type PoA --from 350

One other question, Are all those that are staked still going to be validators, or will it only be the bootnodes that are going to work on PoA?
Thanks,
Nex

**Comment by Stefan-Ethernal** [comment]
> I take it that because we are a live cloud based chain, we can omit the --ibft-validators-prefix-path test-chain- flag and just use this exact line (with our required block height)?
> 
> polygon-edge ibft switch --chain ./genesis.json --type PoA --from 350

Yes, I'd say that's correct. Although, it seems like validators should be provided using `--ibft-validator` flag. In case of using BLS keys, format should be `<validator ECDSA address>:<validator BLS public key>` (otherwise if using ECDSA key types, just validator ECDSA address is enough).

So the complete example would be:
```shell
polygon-edge ibft switch --chain ./genesis.json --type PoA --from 350 \ 
--ibft-validator 0xE0B5aC9785c1Fa3c626B825B3B43B9E5E6BD47Ae:1361d23a017f3fb2e82f2f0422f6ea376785d56d43dfa778ae7d550917255d9b26367eb66f642ce8c2c91b5daa01211c22ea8f222b203aa557cd375474e2543a0eb1b234c7f7d5baa71fa3bf7f07b662b3899fa9e253717a08f443750d6cec1d23541ae39246f0271827458de04b5a2b76250d652fa444ef30dae9c632911ef7 \
--ibft-validator 0xf7eE12C5ADCAc0BB38166D927499291983a7c080:26fc9fb3286c056f3863f3e58b67c3f5aa52e263383d443a8b3fddc30c8eeaf22bb4471465dc16054ce5ea640198cbd0c098124c5a5e83ee55d9a59857fbe65c19bd44b7bb51c6dcff5f10bd2ff366ee4562c64cc7b71d3546d06c9f0b1a846f0e7765bc99378f89cc8d4ec32161abbcb29b99c469cd825a57d74efa8769b896
```

> One other question, Are all those that are staked still going to be validators, or will it only be the bootnodes that are going to work on PoA? Thanks, Nex

AFAIK, validators need to be supplied explicitly by CLI flag when running `ibft switch` command (either by providing `--ibft-validators-prefix` (for local environments) or `--ibft-validator` (for cloud environments).

**Comment by Nexsuperne101** [comment]
@Stefan-Ethernal Thanks for your reply. I'm currently having issues adding and removing nodes. We have 61 validators, and are trying to remove 2 and add 1. Is there a limit on how many can be added to a proposal list, and does that list time out? I tried well over 90% on all nodes to add/remove, but none have gone anywhere. On the ibft snapshot list, I can see 19 votes for one of the 3, and 19 votes for another of the 3, but neither seems to have the 32 votes per node required to add/remove it. Will it time out, so that I can focus on just one node at a time? Thanks, Nex
