### ISSUE TITLE
Node stuck with "unable to verify block, failed to verify the header: invalid signature"

### ISSUE THREAD

**Issue by belbix** [0xPolygon/polygon-edge#1216]
## Description

At some point in time one of the boot node stopped producing new blocks and looping with the error

```
2023-02-10T12:51:56.201Z [WARN]  polygon.server.syncer: failed to complete bulk sync with peer, try to next one: peer ID=error 16Uiu2HAmL7EfRvXTK3GKZ9JGokKYQ398ooFAbKEoU9dFSXQkbfgr="unable to verify block, failed to verify the header: invalid signature"
2023-02-10T12:51:57.840Z [DEBUG] polygon.network.discovery: running regular peer discovery: peer=16Uiu2HAm2Lv1b5mxdKVBVRY44dq8pssa4AeP5ov3NzQPqCpoS1Uz
2023-02-10T12:51:57.841Z [DEBUG] polygon.network.discovery: Querying a peer for near peers: peer=16Uiu2HAm2Lv1b5mxdKVBVRY44dq8pssa4AeP5ov3NzQPqCpoS1Uz
2023-02-10T12:51:57.900Z [DEBUG] polygon.network.discovery: Found new near peers: peer=2
2023-02-10T12:52:00.142Z [DEBUG] polygon.server.ibft: validator message received: type=PREPREPARE height=143948 round=0 addr=0xC148D633E2265C56828d0350157efa4584A49c50
2023-02-10T12:52:00.177Z [DEBUG] polygon.server.ibft: validator message received: type=PREPARE height=143948 round=0 addr=0x651541B17e50feB9D87F583196C58BbAc1e8bbec
2023-02-10T12:52:00.188Z [DEBUG] polygon.server.ibft: validator message received: type=PREPARE height=143948 round=0 addr=0x0B15186BE8acA5B662Cd55143FcA8A6761876302
2023-02-10T12:52:00.201Z [DEBUG] polygon.server.ibft: validator message received: type=COMMIT height=143948 round=0 addr=0x0B15186BE8acA5B662Cd55143FcA8A6761876302
2023-02-10T12:52:00.339Z [DEBUG] polygon.server.ibft: validator message received: type=COMMIT height=143948 round=0 addr=0x651541B17e50feB9D87F583196C58BbAc1e8bbec
2023-02-10T12:52:00.429Z [DEBUG] polygon.server.ibft: validator message received: type=COMMIT height=143948 round=0 addr=0xC148D633E2265C56828d0350157efa4584A49c50
2023-02-10T12:52:01.086Z [WARN]  polygon.server.syncer: failed to complete bulk sync with peer, try to next one: peer ID=error 16Uiu2HAmJHniaE4DmmJz2nvtdfDTZkdL98BoDE5pH7MpjBSVEgGP="unable to verify block, failed to verify the header: invalid signature"
2023-02-10T12:52:02.862Z [DEBUG] polygon.network.discovery: running regular peer discovery: peer=16Uiu2HAmJHniaE4DmmJz2nvtdfDTZkdL98BoDE5pH7MpjBSVEgGP
2023-02-10T12:52:02.864Z [DEBUG] polygon.network.discovery: Querying a peer for near peers: peer=16Uiu2HAmJHniaE4DmmJz2nvtdfDTZkdL98BoDE5pH7MpjBSVEgGP
2023-02-10T12:52:03.140Z [DEBUG] polygon.network.discovery: Found new near peers: peer=2
```

## Your environment
- OS and version.
Ubuntu 20.04
- The version of the Polygon Edge.    
Release version = v0.6.3
- The branch that causes this issue.
https://github.com/0xPolygon/polygon-edge/releases/tag/v0.6.3
- Locally or Cloud hosted (which provider).
Google Cloud
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).
Runned with the command
```
sudo polygon-edge server --secrets-config /opt/polygon-edge/secretsManagerConfig.json --data-dir /opt/polygon-edge/tetu-chain-data-dir --chain /opt/polygon-edge/genesis.json --log-to /opt/polygon-edge/logs/edge_app.log --jsonrpc 0.0.0.0:8545 --libp2p 0.0.0.0:1478 --block-time 1 --price-limit 100000000000 --block-gas-target 100000000 --json-rpc-block-range-limit 100000 --json-rpc-batch-request-limit 10000 --log-level DEBUG --seal
```
## Steps to reproduce
- Tell us how to reproduce this issue.

I had pretty huge traffic on the node and the block time is 1 sec. Probably It was the reason. But no clues in general.

- Where the issue is, if you know.

Probably somewhere around this check
![image](https://user-images.githubusercontent.com/72255836/218097440-ba5bdf0d-c269-4e35-a4a8-1d4325eac25a.png)

- Provide us with the content of your genesis file.

```
{
    "name": "tetu-chain",
    "genesis": {
        "nonce": "0x0000000000000000",
        "timestamp": "0x0",
        "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f90127f90120f84694a8493e726c745978202f240c21d640898cb69480b081db58ffff1a896e628e15ab
1a1d362513cc374f42036a6d539be2e0317cd26d3d591faedeed9fadeb81ae5a7ecc5641f84694651541b17e50feb9d87f583196c58bbac1e8bbecb0b95e657ec74cfa378b1e1de778022780cf2f1af0379cc2b8dc76
1f96afc0731dcd892d5be00e2f1558107d55b97206cff846940b15186be8aca5b662cd55143fca8a6761876302b086e7709a10b65f352626196404b0ef2e582088722f8e03f57f017ac9dba55067cc58f58d5c0dc6e7
fa889f34349d8aa9f84694c148d633e2265c56828d0350157efa4584a49c50b0a9d3d8a53803a5f3ddd6a13e845a531f7003564a0d67bc20bfa387cf2f4a47fd034d1550abca1d60c2f8401fde75237c80c28080",
        "gasLimit": "0x1c9c380",
        "difficulty": "0x1",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "coinbase": "0x0000000000000000000000000000000000000000",
        "alloc": {
            "0x0000000000000000000000000000000000001001": {
....
...
...
                },
                "balance": "0x22b1c8c1227a00000"
            },
            "0xbbbbb8C4364eC2ce52c59D2Ed3E56F307E529a94": {
                "balance": "0x204fce5e3e25026110000000"
            }
        },
        "number": "0x0",
        "gasUsed": "0x70000",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
    },
    "params": {
        "forks": {
            "homestead": 0,
            "byzantium": 0,
            "constantinople": 0,
            "petersburg": 0,
            "istanbul": 0,
            "EIP150": 0,
            "EIP158": 0,
            "EIP155": 0
        },
        "chainID": 778877,
        "engine": {
            "ibft": {
                "epochSize": 100000,
                "type": "PoS",
                "validator_type": "bls"
            }
        },
        "blockGasTarget": 0
    },
    "bootnodes": [
        "/ip4/10.150.0.2/tcp/1478/p2p/16Uiu2HAm8ATSVf5mLAZDKuQBDrtEiYh4qq2NK6rxzPAsmabZKnLg",
        "/ip4/10.170.0.2/tcp/1478/p2p/16Uiu2HAmL7EfRvXTK3GKZ9JGokKYQ398ooFAbKEoU9dFSXQkbfgr"
    ]
}
```

- Provide us with commands that you used to start your validators.

`sudo polygon-edge server --secrets-config /opt/polygon-edge/secretsManagerConfig.json --data-dir /opt/polygon-edge/tetu-chain-data-dir --chain /opt/polygon-edge/genesis.json --log-to /opt/polygon-edge/logs/edge_app.log --jsonrpc 0.0.0.0:8545 --libp2p 0.0.0.0:1478 --block-time 1 --price-limit 100000000000 --block-gas-target 100000000 --json-rpc-block-range-limit 100000 --json-rpc-batch-request-limit 10000 --log-level DEBUG --seal`

- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.

[PEERS LIST]
Number of peers: 3

[0] = 16Uiu2HAmL7EfRvXTK3GKZ9JGokKYQ398ooFAbKEoU9dFSXQkbfgr
[1] = 16Uiu2HAm2Lv1b5mxdKVBVRY44dq8pssa4AeP5ov3NzQPqCpoS1Uz
[2] = 16Uiu2HAmJHniaE4DmmJz2nvtdfDTZkdL98BoDE5pH7MpjBSVEgGP

- Is the chain producing blocks and serving customers atm?

Yes

**Comment by belbix** [comment]
Multiple rebooting and increasing block time to 5 sec did not help.
The node still in a loop with the error and no clues how to recovery it

**Comment by Stefan-Ethernal** [comment]
Hey @belbix, could you please provide logs from the problematic node? Thanks in advance.

**Comment by belbix** [comment]
> Hey @belbix, could you please provide logs from the problematic node? Thanks in advance.

It's just repeated in the loop what I posted. It's a full log
https://ipfs.filebase.io/ipfs/QmSeHaKos5k7tenMbecMUFuU3zSvtCrrYZEa8NXp4XB8Tf

**Comment by Stefan-Ethernal** [comment]
@belbix in order to analyze this issue, we would need some additional information.

Could you do the following:
1. query `eth_blockNumber` JSON RPC endpoint on the bootnode which got stuck

Example (just provide specific JSON RPC endpoint of the bootnode which is stuck):
```shell
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber", "params": []}' <json_rpc_endpoint>
```
2. query `eth_getBlockByNumber` on any other bootnode, which still produces blocks. For block number parameter, provide the block number retrieved in the previous step incremented by one. E.g. if `eth_blockNumber` invocation from previous step returned value 100, you should put here 101 for block number.

Example (in my example, block number is 10, but you should change it accordingly):
```shell
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber", "params": [10, true]}' <json_rpc_endpoint>
```
Provide us output of these two commands if possible. Thanks in advance.

How many nodes are running in the entire cluster? Are there only 3 of them or there are more of them? From what we can see, there were 4 validators written into `ExtraData` of genesis block. So my assumption is that there are 4 of validators, out of which 1 got stuck at some point and is not participating in the consensus atm.

**Comment by belbix** [comment]
unfortunately, I do not have access to these nodes anymore

from what I remember, the node with the issue stoped producing any new blocks and stuck

another boot node produced blocks fine, other nodes also were fine

the whole cluster had 4 nodes: 2 boot nodes, all of them was validators since the genesis

**Comment by Stefan-Ethernal** [comment]
I see. However, without the requested information having on disposal, there is not much we can do in analyzing this issue, since we couldn't reproduce it on our end.

Unfortunately, I don't see there is a possibility to get this node un-stuck from this validation loop. There is slight possibility that completely removing its data, which resides in `blockchain` and `itrie` folders and letting it sync from scratch with peers and see whether it would work (if you feel it is safe to do so).

It is either what you have mentioned that:
- `ProposerSeal`, which is the proposer signature is missing in the block header or 
- `ParentCommittedSeals`, namely signatures on the parent block are invalid which are written into the block header are invalid.

Anyhow, since IBFT is about to be deprecated any time soon and Polybft, the new consensus protocol is going to be delivered going from 0.7.x version, onwards, we strongly encourage using a newer version (however bear in mind that it is not backward compatible). We wouldn't expect that a similar issue should happen on a newer version(s).

Finally, if you notice again similar behavior, you could try following https://github.com/0xPolygon/polygon-edge/issues/1216#issuecomment-1427825226 and provide us an output of JSON RPC endpoints.
