### ISSUE TITLE
Migrate from 0.63 to 0.73

### ISSUE THREAD

**Issue by dorijan** [0xPolygon/polygon-edge#1285]
# [ migrating from 0.63 to 0.73 ]
## Description
Hi to all,
when I tried to run polygon-edge 0.73 with files from 0.63, I got error
`genesis file does not match current genesis`

Is there a way to convert genesis file to new version? Or upgrade path or way?
Thank you

**Comment by Stefan-Ethernal** [comment]
Hello @dorijan, this [page](https://wiki.polygon.technology/docs/supernets/operate/supernets-ibft-to-polybft) contains a described procedure for migrating data from `v0.6.x` to v0.8 onwards. 
Unfortunately, it is not possible to do the migration on `0.7.3` itself, but only from `0.8` onwards, because support for regenesis was implemented and delivered in `0.8` release.
