### ISSUE TITLE
Can not make a deposit from mumbai testnet

### ISSUE THREAD

**Issue by rocky-balboa-1** [0xPolygon/polygon-edge#1367]
# [ bridge issue ]
## Description
I built a L2 net which bridge to mumbai testnet, then called a deposit. However, nothing happened on our L2.

## Your environment
- OS and version: ubuntu 20.04
- The version of the Polygon Edge: 0.8.1

## Steps to reproduce
So, these are the steps that I've done:

- Step 1: clone polygon-edge from github then Make 

- Step 2: create 5 validators
                       go run main.go polybft-secrets --data-dir ./workspace/test-chain- --insecure --num 5

- Step 3: gen the manifest file
                      go run main.go genesis --block-gas-limit 10000000 --bridge-json-rpc https://matic-mumbai.chainstacklabs.com/ --dir ./workspace/genesis.json --epoch-size 30 --manifest ./workspace/manifest.json --premine  0x0000000000000000000000000000000000000000 --validator-set-size 5

- Step 4: init contracts on rootchain (matic-mumbai)
                       go run main.go rootchain init-contracts --deployer-key <my deployer key> --json-rpc https://matic-mumbai.chainstacklabs.com/ --manifest ./workspace/manifest.json

- Step 5: gen the genesis file
                      go run main.go genesis --block-gas-limit 10000000 --bridge-json-rpc https://matic-mumbai.chainstacklabs.com/ --dir ./workspace/genesis.json --epoch-size 30 --manifest ./workspace/manifest.json --premine 0x0000000000000000000000000000000000000000 --validator-set-size 5

- Step 6: run 5 servers
                     go run main.go server --chain ./workspace/genesis.json --data-dir ./workspace/test-chain-1 --grpc-address :5001 --jsonrpc :9545 --libp2p :30301 --log-level INFO --num-block-confirmations 2 

- Step 7: mint some token to deployer wallet on matic-mumbai, under "rootNativeERC20Address": "0xE51171436905F4bed7afE1F0116dF25785673adD"

- Step 8: deposit from matic-mumbai to our net
                     go run main.go bridge deposit-erc20 --amounts 100000000000000000000 --json-rpc https://matic-mumbai.chainstacklabs.com/ --receivers 0xB3419801C8C6CbE9EB2E73d9ceC37170531bEEEE --root-predicate 0x8cD33552f97A5Dc012a907351ee0140Cf68AEC16 --root-token 0xE51171436905F4bed7afE1F0116dF25785673adD --sender-key <my deployer key>

This is where the problem occurs. After depositing, the token amounts is transferred from deployer account to "rootERC20PredicateAddress": "0x8cD33552f97A5Dc012a907351ee0140Cf68AEC16"  
on matic-mumbai (as expected).

However, on the side of our net, I can not find any events that relate to the deposit transaction I did before.

**Comment by Stefan-Ethernal** [comment]
> Step 6: run 5 servers
go run main.go server --chain ./workspace/genesis.json --data-dir ./workspace/test-chain-1 --grpc-address :5001 --jsonrpc :9545 --libp2p :30301 --log-level INFO --num-block-confirmations 2

The problem most probably is because you haven't run any single validator node as a `relayer`. Relayer automatically finalizes deposits on the child chain, by executing bridge transfers.
When starting up Edge child chain, it is recommended that one of the validators is booted up as a relayer. This is accomplished by providing `--relayer` flag in the server command.

**Comment by rocky-balboa-1** [comment]
> > Step 6: run 5 servers
> > go run main.go server --chain ./workspace/genesis.json --data-dir ./workspace/test-chain-1 --grpc-address :5001 --jsonrpc :9545 --libp2p :30301 --log-level INFO --num-block-confirmations 2
> 
> The problem most probably is because you haven't run any single validator node as a `relayer`. Relayer automatically finalizes deposits on the child chain, by executing bridge transfers. When starting up Edge child chain, it is recommended that one of the validators is booted up as a relayer. This is accomplished by providing `--relayer` flag in the server command.

Thanks so much @Stefan-Ethernal for quick replying. I forgot to mention that I have tried including the --seal and --relayer when starting every validators but it still didn't work. The reason why I don't use them this time is that I followed some parameters setting from this file: 
          polygon-edge/e2e-polybft/e2e/bridge_test.go   
and this file: 
          polygon-edge/e2e-polybft/framework/test-server.go

Could you please check the bridge process with mumbai testnet again, maybe there is something wrong with it, because as I know, the deposit process from local rootchain is fine.

Thanks again for your great jobs.

**Comment by Stefan-Ethernal** [comment]
Ok, I see. However, you definitely need one of the validators to be started in a relayer mode in order for those deposits be settled on the Supernets chain automatically. An alternative approach would be executing those deposit state syncs manually, by sending a transaction to the `execute` function in the `StateReceiver` (https://github.com/0xPolygon/core-contracts/blob/dev/contracts/child/StateReceiver.sol#L74-L88), but only after given commitment gets registered by the consensus protocol. 

Now when I have taken a look to your commands more carefully, I see another potential cause of the issue: currently, due to some technical limitations, the minimum commitment size is set to 2. This means that when making deposits of root native tokens, there must be at least two deposits at one time in order for them to be included in the commitment (which represents a batch of bridge events). So if you can, just make at least one or two more deposits and see if it gets executed on the Supernets.

**Comment by rocky-balboa-1** [comment]
That's lots of helpful information. I will try it now and update the result soon.

Thanks a ton!

**Comment by squiddyswap** [comment]
I got a crazy question?  How did you mint to the rootNativeERC20 token?  Also, does option --premine work?

**Comment by squiddyswap** [comment]
@rocky-balboa-1 Were you able to get that to work?

**Comment by rocky-balboa-1** [comment]
Hello @Stefan-Ethernal, 

I was able to make the deposit based on your suggestion. I added a param while generating genesis file, which I thought that might affect the sync process.:

   --tracker-start-blocks

and give it the current number of mumbai testnet.

So, thanks so much for your help again!

@squiddyswap : yes, it worked!

**Comment by Stefan-Ethernal** [comment]
@rocky-balboa-1 you are welcome, glad it worked.

> I added a param while generating genesis file, which I thought that might affect the sync process.:
> --tracker-start-blocks

Yes, this is an essential part of capturing bridge events in a timely manner (without it, deposit bridge event would be captured probably in several weeks or maybe even months).

Closing this issue as done per https://github.com/0xPolygon/polygon-edge/issues/1367#issuecomment-1501666410.

**Comment by andreujuanc** [comment]
Hi @Stefan-Ethernal  and @rocky-balboa-1 Which contract am I supposed to pass to tracker-start-blocks? all of them or just the predicate?

**Comment by rocky-balboa-1** [comment]
Hi @andreujuanc 
Only stateSender contract need to be passed to tracker-start-blocks. Have a nice day!

**Comment by andreujuanc** [comment]
Thanks @rocky-balboa-1

**Comment by deepalt92** [comment]
Hi @rocky-balboa-1, @Stefan-Ethernal and @andreujuanc,
Could you please let me know how you did "Step 7: mint some token to deployer wallet on matic-mumbai, under "rootNativeERC20Address": "0xE51171436905F4bed7afE1F0116dF25785673adD".
How did you mint the rootNativeERC20 to your deployer wallet (e.g., Metamask)? I tried invoking a "mint" function using Truffle but was unable to do so because I don't exactly know the source code of the rootNaticeERC20 token to derive its ABI.

Lastly, how did you check if the deposit had gone through to your Supernet. Did you connect your MetaMask to the Supernet and import the token with the address "0xE51171436905F4bed7afE1F0116dF25785673adD" to verify it shows up on MetaMask?

Thanks in advance!

**Comment by andreujuanc** [comment]
When I was checking out supernets i was doing rpc calls with a script I made.
Also tried importing in MM, and also a local instance of a blockexplorer.
None of them showed anything. :(

**Comment by deepalt92** [comment]
@andreujuanc Thanks for letting me know. Was your script listening to events emitted on the Supernet after the bridge deposit or were you checking for blocks on the Supernet with a transaction from the contract predicate address?
I tried with multiple versions v0.8.1, v0.9 and v1.0.0. Whilst the bridging seemed to have worked on the Rootchain side of things, I couldn't get the tokens transferred from the Rootchain to show up on MetaMask when connected to the Supernet.

@Stefan-Ethernal @rocky-balboa-1 @squiddyswap Could you please confirm that you faced the same issue? and whether you were able to solve it?
There is a comment by @amansk2050  in this issue: https://github.com/0xPolygon/polygon-edge/issues/1628
He has tried with v0.9.0, and has not been able to get the tokens to showup on the Supernet, even though the Deposit ERC20 seemed to have worked on the Mumbai Rootchain. I replicated his steps and faced the same issue. The Deposit from the Rootchain went through but I couldn't get it to showup on MetaMask when connected to the Supernet. 
Just to add to this, I also gave the --relayer flag when starting the validators in the Supernet as recommended in this thread.

**Comment by andreujuanc** [comment]
I didn't try v1.
Will give it a go soon.

**Comment by amansk2050** [comment]
> --tracker-start-blocks

can show me the actual command
because there is no such  flag

**Comment by deepalt92** [comment]
@andreujuanc did you try with --tracker-start-blocks. What parameters did you pass to it? I think you need to pass a contract address and some value. <contract address>: <value>? The contract address is the stateSender, what is the value?
@amansk2050 You need to use version 0.8.1 for the --tracker-start-blocks to show up. Later version don't have it.

**Comment by andreujuanc** [comment]
> @andreujuanc did you try with --tracker-start-blocks. What parameters did you pass to it? I think you need to pass a contract address and some value. <contract address>: <value>? The contract address is the stateSender, what is the value?
> @amansk2050 You need to use version 0.8.1 for the --tracker-start-blocks to show up. Later version don't have it.

Thanks for pointing me to the right direction, but I cannot currently test it. We temporarily park it while we wait for the product to be more stable. I'll give it a go again very soon because it's the best option for us.

**Comment by rocky-balboa-1** [comment]
> @andreujuanc Thanks for letting me know. Was your script listening to events emitted on the Supernet after the bridge deposit or were you checking for blocks on the Supernet with a transaction from the contract predicate address? I tried with multiple versions v0.8.1, v0.9 and v1.0.0. Whilst the bridging seemed to have worked on the Rootchain side of things, I couldn't get the tokens transferred from the Rootchain to show up on MetaMask when connected to the Supernet.
> 
> @Stefan-Ethernal @rocky-balboa-1 @squiddyswap Could you please confirm that you faced the same issue? and whether you were able to solve it? There is a comment by @amansk2050 in this issue: #1628 He has tried with v0.9.0, and has not been able to get the tokens to showup on the Supernet, even though the Deposit ERC20 seemed to have worked on the Mumbai Rootchain. I replicated his steps and faced the same issue. The Deposit from the Rootchain went through but I couldn't get it to showup on MetaMask when connected to the Supernet. Just to add to this, I also gave the --relayer flag when starting the validators in the Supernet as recommended in this thread.

You should try depositing by batch

**Comment by Stefan-Ethernal** [comment]
> > --tracker-start-blocks
> 
> can show me the actual command because there is no such flag

@amansk2050 from v0.9 onwards `--tracker-start-block` flag is removed and the configuration is now populated automatically as part of `rootchain deploy` command.

As for how to deploy a new Supernets, you should be able to get it done by following [documentation](https://wiki.polygon.technology/docs/supernets/operate/deploy/). Generally, we recommend using at least v1.0 if not v1.1, because it is way more mature than the ones prior to v1.0.

**Comment by deepalt92** [comment]
> > > --tracker-start-blocks
> > 
> > 
> > can show me the actual command because there is no such flag
> 
> @amansk2050 from v0.9 onwards `--tracker-start-block` flag is removed and the configuration is now populated automatically as part of `rootchain deploy` command.
> 
> As for how to deploy a new Supernets, you should be able to get it done by following [documentation](https://wiki.polygon.technology/docs/supernets/operate/deploy/). Generally, we recommend using at least v1.0 if not v1.1, because it is way more mature than the ones prior to v1.0.

@Stefan-Ethernal I am not sure whether v1.0 and v1.1 supports bridge transactions both ways. We tried depositing tokens from the Rootchain (Mumbai) to our Supernet and it worked. The child token that was funded on our Supernet was an address we didn't specify. What determines the address that gets funded on the Supernet when we use `./polygon-edge bridge deposit-erc20`

To add to this, I am not sure whether `./polygon-edge bridge withdraw-erc20` works in either v1.0 or v1.1. It at least didn't work for us. We faced the same issue identified in the following bug: https://github.com/0xPolygon/polygon-edge/issues/1753.
 A bug fix has been done on this but has been merged to the `development `branch apparently. Am I correct in thinking that the `./polygon-edge bridge withdraw-erc20` is only supported in the `development` branch and not in either v1.0 or v1.1?

Anyway, I really like what you guys have done in building a bridge based on smart contracts and smart contract events. Hope to see more details on the implementation in the future other than the currently available documentation.

**Comment by amansk2050** [comment]
> > > --tracker-start-blocks
> > 
> > 
> > can show me the actual command because there is no such flag
> 
> @amansk2050 from v0.9 onwards `--tracker-start-block` flag is removed and the configuration is now populated automatically as part of `rootchain deploy` command.
> 
> As for how to deploy a new Supernets, you should be able to get it done by following [documentation](https://wiki.polygon.technology/docs/supernets/operate/deploy/). Generally, we recommend using at least v1.0 if not v1.1, because it is way more mature than the ones prior to v1.0.

tried with version you mentioned but faces same issue, it is getting deposited in erc20predicate contract but not reflecting on supernet

**Comment by amansk2050** [comment]
> > > --tracker-start-blocks
> > 
> > 
> > can show me the actual command because there is no such flag
> 
> @amansk2050 from v0.9 onwards `--tracker-start-block` flag is removed and the configuration is now populated automatically as part of `rootchain deploy` command.
> 
> As for how to deploy a new Supernets, you should be able to get it done by following [documentation](https://wiki.polygon.technology/docs/supernets/operate/deploy/). Generally, we recommend using at least v1.0 if not v1.1, because it is way more mature than the ones prior to v1.0.

version - 1.1.0

command used 
`./polygon-edge polybft stake \
--data-dir ./kaldi-chain-1 \
--amount 1000000000000000000 \
--stake-manager "0xb6Ab15908033CbFE4E6e6313e242B776fDE3c802" \
--stake-token "0x0BaA5a112a64087eB80CfF57fbBD0B4d8011A50B" \
--jsonrpc https://rpc-mumbai.maticvigil.com/ \
--supernet-id 1
`

getting error 
`{"code":3,"message":"execution reverted: Address: call to non-contract","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d416464726573733a2063616c6c20746f206e6f6e2d636f6e7472616374000000"}
`

**Comment by deepalt92** [comment]
> > > > --tracker-start-blocks
> > > 
> > > 
> > > can show me the actual command because there is no such flag
> > 
> > 
> > @amansk2050 from v0.9 onwards `--tracker-start-block` flag is removed and the configuration is now populated automatically as part of `rootchain deploy` command.
> > As for how to deploy a new Supernets, you should be able to get it done by following [documentation](https://wiki.polygon.technology/docs/supernets/operate/deploy/). Generally, we recommend using at least v1.0 if not v1.1, because it is way more mature than the ones prior to v1.0.
> 
> version - 1.1.0
> 
> command used `./polygon-edge polybft stake \ --data-dir ./kaldi-chain-1 \ --amount 1000000000000000000 \ --stake-manager "0xb6Ab15908033CbFE4E6e6313e242B776fDE3c802" \ --stake-token "0x0BaA5a112a64087eB80CfF57fbBD0B4d8011A50B" \ --jsonrpc https://rpc-mumbai.maticvigil.com/ \ --supernet-id 1 `
> 
> getting error `{"code":3,"message":"execution reverted: Address: call to non-contract","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d416464726573733a2063616c6c20746f206e6f6e2d636f6e7472616374000000"} `

Check your stake token, are you using a custom stake token? The staking worked fine for me, and the bridging also worked when depositing tokens from the Rootchain to the Supernet. The withdraw, however, did not work as per my previous comment.

**Comment by amansk2050** [comment]
> > > > > --tracker-start-blocks
> > > > 
> > > > 
> > > > can show me the actual command because there is no such flag
> > > 
> > > 
> > > @amansk2050 from v0.9 onwards `--tracker-start-block` flag is removed and the configuration is now populated automatically as part of `rootchain deploy` command.
> > > As for how to deploy a new Supernets, you should be able to get it done by following [documentation](https://wiki.polygon.technology/docs/supernets/operate/deploy/). Generally, we recommend using at least v1.0 if not v1.1, because it is way more mature than the ones prior to v1.0.
> > 
> > 
> > version - 1.1.0
> > command used `./polygon-edge polybft stake \ --data-dir ./kaldi-chain-1 \ --amount 1000000000000000000 \ --stake-manager "0xb6Ab15908033CbFE4E6e6313e242B776fDE3c802" \ --stake-token "0x0BaA5a112a64087eB80CfF57fbBD0B4d8011A50B" \ --jsonrpc https://rpc-mumbai.maticvigil.com/ \ --supernet-id 1 `
> > getting error `{"code":3,"message":"execution reverted: Address: call to non-contract","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d416464726573733a2063616c6c20746f206e6f6e2d636f6e7472616374000000"} `
> 
> Check your stake token, are you using a custom stake token? The staking worked fine for me, and the bridging also worked when depositing tokens from the Rootchain to the Supernet. The withdraw, however, did not work as per my previous comment.

yes I am using custom stake token,

how to get stake token contract , to deploy ?

**Comment by Stefan-Ethernal** [comment]
> how to get stake token contract , to deploy ?

Stake token can be arbitrary ERC20 token. 
As per how you can deploy it, you can deploy it:
- using Remix IDE (and using Metamask injected environment, that points to the Mumbai). More details can be found [here](https://remix-ide.readthedocs.io/en/latest/create_deploy.html) or 
- foundry tool (more on this procedure [here](https://book.getfoundry.sh/forge/deploying#deploying)).

**Comment by Stefan-Ethernal** [comment]
> @Stefan-Ethernal I am not sure whether v1.0 and v1.1 supports bridge transactions both ways.

Yes it works and we are verifying it in our CI pipelines. Although in our end-to-end tests, we are running against a locally running Geth client, that acts as a rootchain, and that is an isolated environment, where only bridge transactions are found, there occurred some bugs related to gas price estimations were not correct and bridge transactions not being processed in a timely manner. We fixed those bugs recently through: https://github.com/0xPolygon/polygon-edge/pull/1795 and https://github.com/0xPolygon/polygon-edge/pull/1859. It is not yet part of any release but should be delivered with the next release which is around the corner. If you would like to re-test it, then you can use this branch as a next-release preview https://github.com/0xPolygon/polygon-edge/tree/v1.1.1-alternative.

> The child token that was funded on our Supernet was an address we didn't specify. What determines the address that gets funded on the Supernet when we use ./polygon-edge bridge deposit-erc20

Not sure if I have understood your question well, but I think it refers to how the child token address gets determined.
A child token is a minimal proxy/clone of an existing root token (more info on this topic is provided [here](https://blog.openzeppelin.com/deep-dive-into-the-minimal-proxy-contract)). It is basically a clone of [ChildERC20](https://github.com/0xPolygon/core-contracts/blob/main/contracts/child/ChildERC20.sol). Whenever a deposit of a certain root token is made for the first time, the mapping token procedure gets triggered. On the root predicate, it calculates the deterministic address of the child token (https://github.com/0xPolygon/core-contracts/blob/main/contracts/root/RootERC20Predicate.sol#L93-L97) and once that information gets bridged to a child predicate, using state sync mechanism, it deploys `ChildERC20` contract implementation clone to the same address calculated by root predicate (https://github.com/0xPolygon/core-contracts/blob/main/contracts/child/ChildERC20Predicate.sol#L220-L222).
So child token address is not known in advance, but for any root token address, it can be queried by retrieving it from this [mapping](https://github.com/0xPolygon/core-contracts/blob/main/contracts/child/ChildERC20Predicate.sol#L34), that holds root token to child token addresses.

> To add to this, I am not sure whether ./polygon-edge bridge withdraw-erc20 works in either v1.0 or v1.1. It at least didn't work for us. We faced the same issue identified in the following bug: https://github.com/0xPolygon/polygon-edge/issues/1753.

As I have explained in the 1st paragraph, as per the bridge itself, it should work properly in both v1.0 and v1.1 releases, although we have discovered some issues related to setting proper gas prices and some issues on the Edge itself. So with https://github.com/0xPolygon/polygon-edge/pull/1795, we have changed to send dynamic fee transactions instead of legacy ones to a rootchain.

> Hope to see more details on the implementation in the future other than the currently available documentation.

Here are some diagrams, that should better explain bridge mechanics.

## Depositting rootchain originated tokens
![image](https://github.com/0xPolygon/polygon-edge/assets/93934272/f7bda17c-7495-4cb3-8868-07221697cd10)

## Withdrawing rootchain originated tokens
![image](https://github.com/0xPolygon/polygon-edge/assets/93934272/04a45d8b-dea4-4fd9-9649-bca4fba45a2e)

**Comment by deepalt92** [comment]
@Stefan-Ethernal Thank you so much for your detailed reply. Your answer seems to address all my questions. I'll try with: https://github.com/0xPolygon/polygon-edge/tree/v1.1.1-alternative

**Comment by rapidAman** [comment]
hi @deepalt92, are you able to bridge token finally ?, is it showing any balance in your supernet metamask. ?

**Comment by rapidAman** [comment]
> > > > --tracker-start-blocks
> > > 
> > > 
> > > can show me the actual command because there is no such flag
> > 
> > 
> > @amansk2050 from v0.9 onwards `--tracker-start-block` flag is removed and the configuration is now populated automatically as part of `rootchain deploy` command.
> > As for how to deploy a new Supernets, you should be able to get it done by following [documentation](https://wiki.polygon.technology/docs/supernets/operate/deploy/). Generally, we recommend using at least v1.0 if not v1.1, because it is way more mature than the ones prior to v1.0.
> 
> version - 1.1.0
> 
> command used `./polygon-edge polybft stake \ --data-dir ./kaldi-chain-1 \ --amount 1000000000000000000 \ --stake-manager "0xb6Ab15908033CbFE4E6e6313e242B776fDE3c802" \ --stake-token "0x0BaA5a112a64087eB80CfF57fbBD0B4d8011A50B" \ --jsonrpc https://rpc-mumbai.maticvigil.com/ \ --supernet-id 1 `
> 
> getting error `{"code":3,"message":"execution reverted: Address: call to non-contract","data":"0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001d416464726573733a2063616c6c20746f206e6f6e2d636f6e7472616374000000"} `

@andreujuanc @deepalt92  it is saying non contract for stake manager contract because it approving the amount from stake token but not initiating stake from stake manager contract.  I crossed checked the address, I have used proepr address
