### ISSUE TITLE
Funding validators on rootchain Polygon Mumbai

### ISSUE THREAD

**Issue by squiddyswap** [0xPolygon/polygon-edge#1401]
Funding validators on rootchain Polygon Mumbai
we ran this command to deploy and initialize rootchain contracts
./polygon-edge rootchain init-contracts --manifest ./manifest.json --json-rpc https://matic-mumbai.chainstacklabs.com
everthing ran fine all contracts created and initialized.  

But when we ran the funding of the rootchain validators with this command:
./polygon-edge rootchain fund --data-dir test-chain- --num 4 --json-rpc https://matic-mumbai.chainstacklabs.com

we get the result "no accounts registered".  What are we missing here?
## Your environment
- Debian 11 Multiple VMs
- v0.8.1    

## Steps to reproduce
- Tell us how to reproduce this issue.
/polygon-edge rootchain fund --data-dir test-chain- --num 4 --json-rpc https://matic-mumbai.chainstacklabs.com

## Expected behavior
Validators funded
-we get the result "no accounts registered".

**Comment by Stefan-Ethernal** [comment]
It is not intended to be used that way as `rootchain fund` command is intended for testing purposes where we are running local Geth instance in dev mode.

Since the Mumbai network is a public chain, we cannot use `rootchain fund` command but instead need to send MATICs to the validators' addresses on the rootchain.

In order to obtain some MATICs for testing, try with some of the faucets. I have tried this [one](https://faucet.polygon.technology/), but for some reason it doesn't work when acquiring MATICs.

**Comment by squiddyswap** [comment]
Okay @Stefan-Ethernal so when it becomes production, how will this work?  Because, the smart contract predicate address is being created on Mumbai for native tokens how will those native tokens be transferred to the recipient without some type of MATIC for each validator? It says in the docs "Before starting the validator nodes on the childchain, we need to fund them on the rootchain network. This is necessary for validators to be able to send transactions to Ethereum, as they need to have enough funds to cover the gas fees."   When mainnet becomes operational, will you not have to do the same thing on Polygon mainnet???

**Comment by squiddyswap** [comment]
Question is are validators addresses being depolyed on Polygon Mumbai when this command is run?
./polygon-edge rootchain init-contracts --manifest ./manifest.json --json-rpc https://matic-mumbai.chainstacklabs.com

If not, how will this happen  " need to send MATICs to the validators' addresses on the rootchain" ?

**Comment by Stefan-Ethernal** [comment]
> Okay @Stefan-Ethernal so when it becomes production, how will this work? 

Version 0.9 (which is about to be released in the following weeks) is going to introduce the concept of root chain staking. Basically, each validator that wants to participate in the consensus protocol on the child chain, needs to stake on a root chain first as a pre-requisite. After that stake information is bridged to a child chain and a validator is able to participate in the consensus and accumulate rewards.

As per the 0.7 and 0.8 versions, staking is happening on a child chain. However, validators need to have a non-zero root chain balance in order to be able to send checkpoints to a root chain (e.g. for the Mumbai network acting as a root chain, it is MATIC as a native token), which is critical in order to be able to do withdrawals (namely transferring assets from a child chain to a root chain).

In either case, accounts that are going to participate as Supernets/child chain validators, need to have a non-zero balance of a root chain native token associated. It is a pre-requisite.

> "Before starting the validator nodes on the childchain, we need to fund them on the rootchain network. This is necessary for validators to be able to send transactions to Ethereum, as they need to have enough funds to cover the gas fees."

That is correct: each (validator) account should receive some amount of MATICs. This is a manual step which can be performed via Metamask. But first, it would need to have an account that has pre-mined MATIC tokens on the Mumbai network that can re-distribute MATICs to validator account addresses.

> Question is validators' addresses being deployed on Polygon Mumbai when this command is run?

As Edge is Ethereum compatible client, it means that it is using Ethereum-compatible addresses. No need to "deploy" the account to the Polygon Mumbai, but when the validator account receives MATICs for the first time, it is going to be stored in the world state of Mumbai.

**Comment by squiddyswap** [comment]
@Stefan-Ethernal Thanks for the response and thanks for the great job on Polygon Supernets.  I will be anxiously awaiting the next release.
