### ISSUE TITLE
0.8.1 Bridge question (discussions not working)

### ISSUE THREAD

**Issue by andreujuanc** [0xPolygon/polygon-edge#1483]
Hi! 

I wanted to post in "discussions" but it seems that it's not working, so I post it here. (sorry)

![image](https://github.com/0xPolygon/polygon-edge/assets/360052/1b10c515-6c3b-445e-9018-342af31fe43b)

Few questions:
 - After depositing, how can I know what's the address of the child token so I can get its balances.
 - I get a child tx after each epoch, but nothing happens when depositing. My validators are funded, is it a bug in 0.8.1?

**Comment by vcastellm** [comment]
> * After depositing, how can I know what's the address of the child token so I can get its balances.

After the first deposit of a new token, the corresponding token is deployed and mapped in the childchain, the address should be in the logs.

> * I get a child tx after each epoch, but nothing happens when depositing. My validators are funded, is it a bug in 0.8.1?

You mean end of epoch transaction? can you try with 0.9?

Feel free to reopen if not working.

**Comment by andreujuanc** [comment]
Hi @vcastellm ! I found a discord channel dedicated to this, i'll be posting my findings there. I have migrated to 0.9 and still did not manage to get the token in the childchain. 
I've been posting my setup here: https://github.com/andreujuanc/polygon-supernets

What do you think?

**Comment by goran-ethernal** [comment]
Hey @andreujuanc , there was a limitation where at least 2 deposits had to be made so that the state sync commitment gets committed to the `StateReceiver` contract, before the `relayer` can execute those deposits on `L2`. Of course, one of the nodes had to be started with `--relayer` flag. This was recently changed: https://github.com/0xPolygon/polygon-edge/pull/1475. Now we support one deposit per commitment, but it's not in any release yet.

Can you see if this is the case? That you only had one deposit. And can you check does everything get executed after you place a second deposit.

**Comment by andreujuanc** [comment]
Thanks @goran-ethernal  will give it a go.
