### ISSUE TITLE
Panic using `--libp2p 0.0.0.0:port` option

### ISSUE THREAD

**Issue by mrwillis** [0xPolygon/polygon-edge#160]
### Description

Running `polygon-sdk server --libp2p 0.0.0.0:10001` fails without passing a `--nat`

### Your environment

* OS and version Ubuntu 20
* version of the Polygon SDK 96be90487c144f7b1589ac65aad3f741c81644e3
* branch that causes this issue `develop`

### Steps to reproduce

* Tell us how to reproduce this issue <br /> Run `polygon-sdk server --libp2p 0.0.0.0:10001` with a genesis file 
* Where the issue is, if you know <br /> `AddrInfoToString` seems to not like when there are two addresses in the libp2p address info. It's giving me two addresses, 

```go
// AddrInfoToString converts an AddrInfo into a string representation that can be dialed from another node
func AddrInfoToString(addr *peer.AddrInfo) string {
	fmt.Print(addr)
	if len(addr.Addrs) != 1 {
		panic("Not supported")
	}
	return addr.Addrs[0].String() + "/p2p/" + addr.ID.String()
}

```
Gives
```
{16Uiu2HAm7dBcv1avSV8TVFZQV4kUNYi5N1jHu7C4xH1gV58McZx2: [/ip4/192.168.1.248/tcp/10002 /ip4/127.0.0.1/tcp/10002]}

```

### Logs

```
panic: Not supported

goroutine 1 [running]:
github.com/0xPolygon/polygon-sdk/network.AddrInfoToString(0xc0005a04e0, 0x0, 0x0)
	/home/julian/sx-network/polygon-sdk/network/server.go:595 +0x1f7
github.com/0xPolygon/polygon-sdk/network.NewServer(0x1582748, 0xc0002f4cb0, 0xc000100eb0, 0x0, 0x0, 0x0)
	/home/julian/sx-network/polygon-sdk/network/server.go:138 +0xe71
github.com/0xPolygon/polygon-sdk/server.NewServer(0x1582748, 0xc0002f4b60, 0xc0002f8f80, 0x0, 0x0, 0x0)
	/home/julian/sx-network/polygon-sdk/server/server.go:92 +0x5ef
github.com/0xPolygon/polygon-sdk/command/server.(*ServerCommand).Run(0xc00000ed08, 0xc000032260, 0x4, 0x4, 0x0)
	/home/julian/sx-network/polygon-sdk/command/server/server_command.go:187 +0x3de
github.com/mitchellh/cli.(*CLI).Run(0xc00013f7c0, 0x0, 0x0, 0x0)
	/home/julian/sx-network/polygon-sdk/vendor/github.com/mitchellh/cli/cli.go:255 +0xb7d
main.Run(0xc000032250, 0x5, 0x5, 0x0)
	/home/julian/sx-network/polygon-sdk/main.go:25 +0x151
main.main()
	/home/julian/sx-network/polygon-sdk/main.go:12 +0x7c
```

### Proposed solution

If you pass a `--nat`, this error disappears. I feel like this should not be a panic.

**Comment by zivkovicmilos** [comment]
Hey @mrwillis,

Thank you for reaching out.

The issue you're facing is you're setting the `host` for libp2p to be `0.0.0.0`, which is a special value for libp2p, instructing it to listen on **all** interfaces for incoming connections, instead of just one. This is a feature of the standard libp2p library we're using for networking.
When you check `addr.Addrs` it returns all of the interfaces that the host is listening on, which I belive is always > 1.

A workaround would be to specify a host with the `--nat` flag, as you've already mentioned.

I'm not sure why the panic is there, I'll check it out and raise a PR.
I'll also update the issue here once the PR is up.

**Comment by zivkovicmilos** [comment]
Hey @mrwillis,

PR is up, awaiting review 🚀 
https://github.com/0xPolygon/polygon-sdk/pull/171
