### ISSUE TITLE
How do I setup an existing custom ERC20 token as the native gas token?

### ISSUE THREAD

**Issue by giovanni-pucci** [0xPolygon/polygon-edge#1618]
# Setting up an existing custom ERC20 token as the native token
## Description
I'd like some help with setting a custom ERC20 that already exists in the rootchain as the native gas token in the supernets for both use cases:

- For minting this token directly on the supernets.
- For bridging this token from the rootchain to supernets and vice-versa.

Is there a documentation any of you could point me to? If not, could you please document a short example of how to get this to work, in this thread?

## Your environment
- Polygon Edge v1.0.0-rc1
- Branch: tags/v1.0.0-rc1

**Comment by Stefan-Ethernal** [comment]
Hey @giovanni-pucci, this is how we can configure the existing rootchain ERC20 token to act as a native token on the Supernets.

1. when bootstrapping Supernets, run the `rootchain deploy` command and provide the existing rootchain ERC20 token via the `--erc20-token` flag. This will automatically map the existing rootchain ERC20 token to the native token (which means that the native token on the Supernets is basically a child token to the existing rootchain token).
2. run bridge `deposit-erc20` CLI command. Provide a `--root-token` flag with the address of the existing rootchain ERC20 token (the same one provided in the 1st step). Also, provide an actual address for `--root-predicate` (it should be the address of RootERC20Predicate, which is written in the genesis.json as a part of `bridge.erc20PredicateAddress` configuration), `--json-rpc` URL that points to the rootchain node, `--private-key` of an account which makes bridge transaction, etc.

> For minting this token directly on the supernets.

Bear in mind, that if using this approach, then minting a native token independently from the bridge workflow is not allowed, since it could create a disbalance between the total supply of the token on the rootchain compared to the native token supply Supernets (since you could mint it more than the total supply on the rootchain is).

**Comment by tandooricodes** [comment]
Hi @Stefan-Ethernal thanks for the clarification.
Is the `deposit --erc20-token` command intended solely for this condition where the native Supernet token is mapped with a Rootchain ERC20?

**Comment by Stefan-Ethernal** [comment]
> Is the deposit --erc20-token command intended solely for this condition where the native Supernet token is mapped with a Rootchain ERC20?

If you are referring to the `bridge deposit-erc20`, it can be used for depositing arbitrary erc20 tokens. When some token is deposited for the first time, it is going to be mapped automatically on the root chain and the child chain.

On the other hand, if you were referring to the `rootchain deploy` command, by providing `--erc20-token`, indeed that one is mapped to the native non-mintable Supernets token.

**Comment by sahil3Vedi** [comment]
@Stefan-Ethernal I tried mentioning `--erc20-token` and received the following error:

Command:
```
./polygon-edge rootchain deploy --deployer-key $DEPLOYER_KEY --stake-manager $STAKE_MANAGER --stake-token $ROOTCHAIN_STAKE_TOKEN --erc20-token $ROOTCHAIN_PARENT_TOKEN --genesis ./genesis.json $ROOTCHAIN_RPC
```
Output:
```
Error: if child chain native token is mintable, root native token must not pre-exist on root chain
```

According to the error the native token must not pre-exist on the rootchain. Does pre-exist imply that the `totalSupply()` must be 0 or that the contract must not be deployed at all? I have used [a mintable ERC20 on the rootchain](https://mumbai.polygonscan.com/address/0xaADBC81Dec3D3f27a23b9fC8d9F1f031034079e6) without any supply.

Kindly let me know if I have made a mistake,
Regards!
