### ISSUE TITLE
make generate-smart-contract-bindings breaks contractsapi.go

### ISSUE THREAD

**Issue by wolfwolker** [0xPolygon/polygon-edge#1660]
# [ Subject of the issue ]
## Description
After executing `make generate-smart-contract-bindings` the file consensus/polybft/contractsapi/contractsapi.go has uncommited changes on it (not pasting the diff here coz it is huge), which makes to crash any attempt of starting a network using polybft with or without docker.

I've also realized that `make generate-smart-contract-bindings` runs 
```
go run ./consensus/polybft/contractsapi/artifacts-gen/main.go
go run ./consensus/polybft/contractsapi/bindings-gen/main.go
```
but in the readme.md file in the docker folder, only `go run ./consensus/polybft/contractsapi/artifacts-gen/main.go` is documented. Executing only this command and not the make one, the crash disappears.

- Tried develop branch and 1.0-rc1
- Tried ubuntu 22.04 and macOS
- All attempts using scripts/cluster with --docker and without the flag
- I've noticed using ibft does not crash

And this is the error:

```
./scripts/cluster polybft --docker
# github.com/0xPolygon/polygon-edge/consensus/polybft
consensus/polybft/contracts_initializer.go:107:4: unknown field 'NewUseAllowList' in struct literal of type contractsapi.InitializeChildERC20PredicateACLFn
consensus/polybft/contracts_initializer.go:108:4: unknown field 'NewUseBlockList' in struct literal of type contractsapi.InitializeChildERC20PredicateACLFn
consensus/polybft/contracts_initializer.go:109:4: unknown field 'NewOwner' in struct literal of type contractsapi.InitializeChildERC20PredicateACLFn
note: module requires Go 1.20
make: *** [run-docker] Error 2
```

Ibft works fine

## Your environment
- ubuntu 22.04, go 1.20 (but also tried 1.19), node 18 (also tried node 20)
- 1.0-rc1 and develop  
- Locally (macOS) and gcp.

## Steps to reproduce
- make download-submodules
- make compile-core-contracts
- make generate-smart-contract-bindings
- make run-docker

**Comment by Stefan-Ethernal** [comment]
The issue is that `ChildERC20PredicateAccessList` declares two `initialize` functions with different parameters. Once it is compiled, JSON artifact first contains the one with less parameters (defined in the parent contract `ChildERC20Predicate`), and the next one is the proper one defined by the `ChildERC20PredicateAccessList`.

Since we are relying on the `ethgo` library that has abstractions for the smart contracts' ABI and it relies on a mapping between the function name and the function object itself, it does not support multiple functions with the same name in a contract.

That being said, at least for now, we can provide the following workaround for it:
1. head to `core-contracts/artifacts/contracts/child/ChildERC20PredicateAccessList.sol/ChildERC20PredicateAccessList.json`
2. move the `initialize` function with fewer parameters below the one with `newUseAllowList`, `newUseBlockList` and `newOwner` in the JSON
3. re-run `make compile-core-contracts` and errors should be gone.

Btw, if running `make compile-core-contracts` it is not necessary to run `make generate-smart-contract-bindings` separately as the `compile-core-contracts` already generates Golang stubs for it.

**Comment by wolfwolker** [comment]
I can confirm it works following the workaround steps.

Thanks @Stefan-Ethernal !
PS: completely agree and was aware of your last paragraph, added both steps in the ticket description aiming to be more explicit
