### ISSUE TITLE
Unstaking on rootchain

### ISSUE THREAD

**Issue by polygomic** [0xPolygon/polygon-edge#1661]
How can we unstake on rootchain
when we see unstake command there is
polygon-edge polybft unstake -h

Unstakes the amount sent for validator or undelegates amount from validator

Usage:
   polybft unstake [flags]

Flags:
      --amount string     amount to unstake from validator
      --config string     the path to the SecretsManager config file, if omitted, the local FS secrets manager is used
      --data-dir string   the directory for the Polygon Edge data if the local FS is used
  -h, --help              help for unstake
      --jsonrpc string    the JSON-RPC interface (default "0.0.0.0:8545")

Global Flags:
      --json   get all outputs in json format (default false)

it seams it only can work on sidechain not root chain
how should I unstake amount on rootchanin from Stake Manager  contract

## Your environment
- OS and version.
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by Stefan-Ethernal** [comment]
The envisioned workflow for the unstaking is the following:
1. **initiate unstaking** - send a transaction to the [`ValidatorSet.unstake`](https://github.com/0xPolygon/core-contracts/blob/main/contracts/child/validator/ValidatorSet.sol#L84-L87) function (that is exactly what the `unstake` command is doing). It is going to register a withdrawal and after at least 1 epoch (which is currently set for withdrawal waiting period), it is possible to do the withdrawal itself,
2. **unstake finalization (Supernets/child chain)** - send a transaction to the [`ValidatorSet.withdraw`](https://github.com/0xPolygon/core-contracts/blob/main/contracts/child/validator/ValidatorSet.sol#L92-L98) function. It updates the withdrawal queue and [creates](https://github.com/0xPolygon/core-contracts/blob/main/contracts/child/validator/ValidatorSet.sol#L97) bridge exit event, which is later going to be propagated to the root chain's `CustomSupernetManager` contract,
3. **unstake finalization (root chain)** - extract the `L2StateSynced` log from the `withdraw` transaction receipt (we are interested in the first parameter here, which denotes exit event id). When the current epoch elapses and the checkpoint transaction is eventually sent to the root chain, invoke the `bridge exit` CLI command, which is going to acquire exit event proof and send the exit transaction to the `ExitHelper` contract (https://github.com/0xPolygon/core-contracts/blob/main/contracts/root/ExitHelper.sol#L36-L43). It is important to outline that account that sends exit transactions, needs to have enough root chain gas tokens in order to cover transaction fees.

P.s. we are aiming to improve the UX of withdraw command so that a user is aware of exit event id and block number when that transaction got included on the Supernets.
