### ISSUE TITLE
Starting a supernets without pre-mining as the tokens should come through the bridge

### ISSUE THREAD

**Issue by giovanni-pucci** [0xPolygon/polygon-edge#1674]
# The supernets should start with 0 tokens
## Description
Hi! We're setting up a pre-prod environment in which case would require the tokens to come from the Polygon Rootchain.

Essentially, I've remove the `--premine` flag and it worked fine. But when I tried to remove the `--reward-wallet` flag, the genesis fails and the genesis.json file is not generated.

In our understanding, setting up the  **reward-wallet** would cause the tokens to be pre-mined in the child chain, causing a disbalance of the total supply.

We need to understand how can we setup a supernets without having the token premined? Or if it's required, how can we resolved the balance issue on the total supply of the rootchain erc20 token?

Summarizing what we need: We need the tokens to come from an existing erc20 token on the rootchain, they cannot exist out of the box on the supernets.

## Your environment
- v1.0.0-rc
- Cloud hosted (AWS).
- Not running in containerized environment.

## Steps to reproduce
- Simply not have the `--reward-wallet` flag set during the genesis.

## Expected behavior
- **Expected:** We should be able to have a chain with 0 tokens or gas tokens so the tokens can come from a bridge proxying the rootchain erc20 token.
- **Current:** The supernets fails to generate the genesis.json file if the `--reward-wallet` is removed, giving us no chance to start the chain and validate the process.

**Comment by goran-ethernal** [comment]
This is already done, and included in the official v1.0.0 that was released last night. Take a look at this PR:
https://github.com/0xPolygon/polygon-edge/pull/1598

But please, keep in mind (and this is very important): First transaction on supernet (when using non-mintable token), has to be depositing some funds from L1 to L2 to the `relayer` node, so that it can have funds to execute other bridge transactions on L2. Initially, EDGE gas price is 0 until someone sets it on the first transaction sent on EDGE.

As per reward wallet, you can premine it with 0, and transfer tokens to it after you do deposit to the relayer node first.
