### ISSUE TITLE
Change Gaslimit after Genesis Block 

### ISSUE THREAD

**Issue by NoVa-Toast** [0xPolygon/polygon-edge#1903]
Is there a way to Change the Block Gas limit after the First start of the Chain?

**Comment by NoVa-Toast** [comment]
Bump

**Comment by Stefan-Ethernal** [comment]
Hey @NoVa-Toast, it is possible to accomplish it, using the `--block-gas-target` in the `server` command. 

However, when calculating the new block gas limit for each block, since parent block gas limit has an impact on it, it does not mean that necessarily configured block gas target will be reached within the next block, but if set to all validator nodes equally, it is going to gradually increase until it is eventually reached at some point. This is due to the fact that gas limit can be increased at most by the delta, which is calculated by dividing the parent block gas limit by 1024.

Here is the algorithm that calculates and adjusts the gas limit for each block: https://github.com/0xPolygon/polygon-edge/blob/f2b24e79912802b1b6c8fb3ba1abdbcc9eec94c0/blockchain/blockchain.go#L357-L385 (`blockGasTarget` represents value that is configured on a given server instance).
