### ISSUE TITLE
GenesisProxy contract not found inside the core contracts repo

### ISSUE THREAD

**Issue by tandooricodes** [0xPolygon/polygon-edge#1911]
Hi @stana-miric , 
I noticed that in a recent commit a GenesisProxy contract was added to the docker-compose flow.
https://github.com/0xPolygon/polygon-edge/blame/f2b24e79912802b1b6c8fb3ba1abdbcc9eec94c0/consensus/polybft/contractsapi/artifacts-gen/main.go#L208

However, if we check the core-contracts repo: https://github.com/0xPolygon/core-contracts/tree/main/contracts/lib, 
there is no contract under `lib/GenesisProxy.sol`

These are steps we followed when trying to run the `docker-compose` workflow:
## 1. Cloning repo:
```
git clone https://github.com/0xPolygon/polygon-edge.git
cd polygon-edge
```
## 2. Install core-contracts
```
make download-submodules
```
## 3. Compile Contracts
```
cd core-contracts && npm install && npm run compile && cd -
go run ./consensus/polybft/contractsapi/artifacts-gen/main.go
```

However, when executing the last command this error is received:
```
open /home/one/Desktop/supernets-docker/polygon-edge/core-contracts/artifacts/contracts/lib/GenesisProxy.sol/GenesisProxy.json: no such file or directory
exit status 1
```

Kindly let us know how this can be reconciled, thanks for your time!

**Comment by Stefan-Ethernal** [comment]
Hey @sahil3Vedi, this contract was there and for some reason, it got removed, without noticing the Supernets client team through this PR: https://github.com/0xPolygon/core-contracts/pull/361.

Anyway, since the Supernets client already comes with an appropriate set of smart contracts, that are pre-compiled and shipped alongside with Supernets codebase itself, I'm curious why you compile contracts on your own and generate artifacts manually. It is a redundant step. You should be able to checkout an arbitrary branch and just run `docker compose up` (from `docker/local` folder) to spin up a locally running Supernets.

**Comment by tandooricodes** [comment]
Thanks for the clarification @Stefan-Ethernal
