### ISSUE TITLE
1.3 Breaks the ability to inject bytecode to the genesis file 

### ISSUE THREAD

**Issue by RonTuretzky** [0xPolygon/polygon-edge#1979]
# [ Injection not working anymore]
## Description
With release 1.1 we put the following lines of code 
```
new_code=$(jq -r .deployedBytecode artifacts/contracts/child/polygon/ValidatorSet.sol/ValidatorSet.json)
  jq --arg new_code "$new_code" '.genesis.alloc["0x0000000000000000000000000000000000000101"].code |= $new_code' genesis.json > tmpfile && mv tmpfile genesis.json
```

into the cluster script in the createGenesis() command in order to introduce custom functionality from a homebrewed implementation of the validatorset, with all features working as expected. 
Now, we get the following error at the end of the cluster script ( this output is from the validator server command) 

![image](https://github.com/0xPolygon/polygon-edge/assets/74178515/8b466f70-3479-4aff-b734-cd696cf52230)

## Your environment
- Ubuntu 22.04
- 1.3
- ad1cf7b
- Locally hosted
- validators are running under containerized environment (Docker)

## Steps to reproduce
- Inject bytecode into the genesis file for a custom implementation of any of the system contracts and proceed as usual 
- Which commands triggered the issue, if any.

## Expected behavior
- Supernet should run with the custom smart contract implementation (worked consistently in the past)

**Comment by Stefan-Ethernal** [comment]
This is still possible, but now on this address (`0x0000000000000000000000000000000000000101`) proxy contract is deployed instead of in this case, the `ValidatorSet` contract itself.

You would need to inject a custom `ValidatorSet` implementation to this address, instead `0x0000000000000000000000000000000000001011`.

So basically each genesis contract address used before for implementation logic contracts is now reserved for the `GenesisProxy` contract and suffix 1 is added to the address of each proxy contract to determine each implementation logic contract address.

e.g. 
- `ValidatorSet` (proxy address: `0x0000000000000000000000000000000000000101`, implementation address: `0x0000000000000000000000000000000000001011`)
- `NativeERC20` aka native token contract (proxy address: `0x0000000000000000000000000000000000001010`, implementation address: `0x0000000000000000000000000000000000010101`)

**Comment by RonTuretzky** [comment]
Thank you!
