### ISSUE TITLE
JSON RPC filtering 'committed' signature field from the extraData

### ISSUE THREAD

**Issue by ArielLaub** [0xPolygon/polygon-edge#2047]
I've written a JSON RPC websocket client that connects to my polygon edge cluster.
the application subscribes for 'block' and receives a new block triggering code that parses the extraData field from the block header.
Everything works as expected, except the 'committed' signature which is alway [0, 0]. Looking in the codebase I see this is indeed filtered out (FilterExtra that calls GetIbftExtraClean).
I need this field because I want to create a 'virtual' checkpoint corresponding to the current block. (even if it's not a candidate for actually creating a checkpoint on L1, as explained I'm doing this off chain).
The 'parent' signature is working fine and I am using it to create such a virtual checkpoint for the previous block. That is a workaround but I don't want to have this 1 block lag in production

Why is this filtering there in the first place?

I'm using PolyBFT consensus and running version 1.3 but I also checked the development branch.

**Comment by RonTuretzky** [comment]
bumping. also experienced it on my end @Stefan-Ethernal

**Comment by Stefan-Ethernal** [comment]
> Why is this filtering there in the first place?

The `Committed` field is filtered out, because BLS aggregated signatures of the current block is not finalized then, but on the next one. This is the case because different nodes could retrieve different signatures on their end, so in order to mitigate this situation, we are waiting for the next block to gather consensus around those data (`Parent` field). 

Block hash calculation does not include `Committed` field so when returning a `Block` object from `eth_getBlockByNumber`, we are filtering out `Committed` field, in order to have the same data on disposal as for the consensus protocol.

**Comment by ArielLaub** [comment]
Thanks Stefan, that makes sense. Lets say I do expose the committed signature via eth_getBlockByNumber (on my own fork), I understand the aggregated signature is not finalized yet and that different nodes might have different values but do these committed signatures represent enough stake for a consensus? will I be able to verify a 'virtual' checkpoint I've created from the current extra with similar logic to what is used in the root chain CheckpointManager?
The motivation is I need to extract exit events from the current block and be able to verify them given a proof (and the checkpoint data) and I don't want to have a lag of one block.

**Comment by Stefan-Ethernal** [comment]
> but do these committed signatures represent enough stake for a consensus

Yes, there is more than a quorum size of voting power in the committed aggregated signatures, so you should be able to verify the checkpoint.

Basically, we have decided to filter out the committed field, because there was an issue in the past, the hash for the block was different when calculated by block data compared to the hash written in the header. That was because we were calculating a hash of the block based on extra data without the signatures for the current block and we were returning back header including the committed field as well (which is not yet considered finalized).

**Comment by ArielLaub** [comment]
Thanks Stefan! Understood the reasoning behind hiding the committed signature and got all the information I needed. I'm closing this issue.
