### ISSUE TITLE
execution reverted: PRECOMPILE_CALL_FAILED when minting Native Token

### ISSUE THREAD

**Issue by saurabh-lodha-16** [0xPolygon/polygon-edge#2087]
# [ Native Token Mintable gives PRECOMPILE_CALL_FAILED error  ]
## Description
I have setup Polygon Supernets with the native token as mintable. When I complete all the steps for the setup and proceed with the minting, I am not able to mint more than 1 ETH.

## Your environment
- Ubuntu 22.04 LTS
- Polygon Edge Version: 1.3.2
- develop
- Cloud Hosted. AWS
- Validators are running with NoHup

## Steps to reproduce
- Tell us how to reproduce this issue.
I followed the guide for setting up Supernets. https://github.com/integrations-Polygon/Supernets-Edge-Tutorials/blob/master/Supernets_v1.3_setup.md

I managed to do it successfully and this is my network.
```
Network Name - Supernets
RPC - https://www.mainnetfork.online/
ChainID - 6969
Symbol - ETH
```

- Provide us with the content of your genesis file.
[genesis.json](https://github.com/0xPolygon/polygon-edge/files/13927945/genesis.json)

- Provide us with commands that you used to start your validators.
```
nohup ./polygon-edge server --data-dir ./test-chain-1 --chain genesis.json --grpc-address :5001 --libp2p :30301 --jsonrpc :9545 --log-level DEBUG --relayer > node1.log 2>&1 &
```
- Is the chain producing blocks and serving customers atm?
Yes. Every other functionality works like contract deployment, ERC20 token transfers etc.

## Expected behavior
- Tell us what should happen.
Since the native token is mintable, it should mint to the address entered in the argument.

- Tell us what happened instead.

I am not able to mint and get the below error.
<img width="1440" alt="Screenshot 2024-01-13 at 5 51 50 PM" src="https://github.com/0xPolygon/polygon-edge/assets/47684949/a812a9fb-e977-409b-9f06-325c29ca4720">

The minting works if I try to mint less than 1 ETH and it proceeds in the perfect way.
This is the contract I am using for Minting - 

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts@4.0.0/token/ERC20/ERC20.sol";

contract SuperETH is ERC20 {
    constructor()
        ERC20("SuperETH", "SETH")
    {
    }

    function mint(address account, uint256 amount) public{
        _mint(account, amount);
    }
}
```

I also get the error during gas estimation -
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32600,
        "message": "unable to apply transaction even for the highest gas limit 5242880: execution reverted"
    }
}
```

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by saurabh-lodha-16** [comment]
@Stefan-Ethernal can you please check this as this is super core to my operation.

**Comment by tandooricodes** [comment]
Hey @saurabh-lodha-16,

A note regarding the Supernets v1.3 setup tutorial you followed (https://github.com/integrations-Polygon/Supernets-Edge-Tutorials/blob/master/Supernets_v1.3_setup.md).

In this guide, when creating the genesis file, the native Supernet token is set to be unmintable. This is because it's linked to the Rootchain Parent Token (which is an ERC20 Token on the Rootchain). Therefore, the only method to increase the Native Tokens on the Supernet is by bridging Rootchain Parent Tokens from the Rootchain to the Supernet.

However, there's an alternative setup approach where:

- The Supernet native token is mintable.
- The Rootchain Parent Token isn't linked to the Supernet's native token.

You can find this setup in the v1.1.0 tutorial here: https://github.com/integrations-Polygon/Supernets-Edge-Tutorials/blob/master/Supernets_v1.1.0_setup.md, and it should be compatible with v1.3.

Let us know if this helps!

**Comment by saurabh-lodha-16** [comment]
Thanks for answering this as we were super stuck on this. @sahil3Vedi 
I had made the native token mintable in the config.
I read the docs and had made it so.

Can you please share the exact step related to not linking it to Rootchain Parent Token ?
Would love to understand the issues in this setup ?

**Comment by saurabh-lodha-16** [comment]
Also @sahil3Vedi  is it possible to modify this in an existing setup ?
Lastly I did not understand why minting less than 1 Ether works ?

**Comment by tandooricodes** [comment]
Hi @Stefan-Ethernal need your attention here.
The user is unable to mint tokens on the Supernet when the amount exceeds 1ether.

**Comment by Stefan-Ethernal** [comment]
Hey @saurabh-lodha-16, native token you are interacting with is deployed to `0x0...1010` address automatically, in genesis time. So basically you are not interacting with the `SuperETH` contract you have provided, but with the `NativeERC20Mintable`. It represents an ERC20 wrapper around native/gas token in the Blade (that indeed is called `SuperETH`). 

The following code snippet provides just a glimpse of implementation and some parts are intentionally left out for brevity reasons (full implementation can be seen [here](https://github.com/0xPolygon/core-contracts/blob/main/contracts/child/NativeERC20Mintable.sol).

```go
contract NativeERC20Mintable is Context, Initializable, System, Ownable2Step, IERC20Metadata {
    modifier onlyPredicateOrMinter() {
        require(msg.sender == _predicate || msg.sender == owner(), "NativeERC20: Only predicate or owner can call");

        _;
    }

    /**
         * @notice Mints an amount of tokens to a particular address
         * @dev Can only be called by the predicate address
         * @param account Account of the user to mint the tokens to
         * @param amount Amount of tokens to mint to the account
         * @return bool Returns true if function call is successful
         */
    function mint(address account, uint256 amount) external virtual onlyPredicateOrMinter returns (bool) {
        _mint(account, amount);

        return true;
    }

    function _mint(address account, uint256 amount) internal virtual {
        require(account != address(0), "ERC20: mint to the zero address");

        _totalSupply += amount;

        // slither-disable-next-line reentrancy-events,low-level-calls
        (bool success, bytes memory result) = NATIVE_TRANSFER_PRECOMPILE.call(abi.encode(address(0), account, amount)); // solhint-disable-line avoid-low-level-calls
        require(success && abi.decode(result, (bool)), "PRECOMPILE_CALL_FAILED");

        emit Transfer(address(0), account, amount);
    }
}
```

## What is specific to NativeERC20Mintable?
Unlike other ERC20 tokens (non-native ones), this one in particular relies on world state account balances directly, by relying on the native transfer precompile, provided by the Edge. Mint operation represents transferring from `0x0` address to a recipient account address and burn is the opposite process (transferring from sender account address to `0x0` address).

The reason you are not able to mint more than 1 native token is because that is how many tokens you have premined to the `0x0` address in the genesis command. This can be seen from the provided genesis definition (0xde0b6b3a7640000=10^18weis=1 native token):

```json
"alloc": {
     "0x0000000000000000000000000000000000000000": {
         "balance": "0xde0b6b3a7640000"
     },
     // other parts left out for brevity
}
```
## How to resolve the issue?
Feel free to re-run the bootstrap setup from scratch and provide some enormous amount of tokens via the `--premine` flag to the `0x0` address in order to be able to cover all future mint operations.

**Comment by saurabh-lodha-16** [comment]
Hey @Stefan-Ethernal I was away for the week so did not manage to test this.
Really thanks for the detailed reply and for explaining me what's the root cause of this error.
I will try this out and will update here once it works.
Thanks again.

**Comment by saurabh-lodha-16** [comment]
@Stefan-Ethernal I have one question though.
When the token is mapped to a Rootchain ERC20 token, can you please share the steps on how to bridge the tokens in this case ?
If the token is not mapped and is made mintable, this means that there is no control over the Rootchain and whatever tokens we add in the genesis as you mentioned above, can be minted right ? Are there any issues to this setup ?

**Comment by Stefan-Ethernal** [comment]
> When the token is mapped to a Rootchain ERC20 token, can you please share the steps on how to bridge the tokens in this case ?

The following paragraphs explain how bridging from a rootchain to a child chain is done when a token originates from a rootchain (namely its supply is controlled over there: minting and burning). Given example explains how ERC20 tokens are bridged from a rootchain to a child chain, but workflow is similar to any other asset type (ERC721 or ERC1155). The only difference is that `bridge deposit-erc721` or `bridge deposit-erc1155` commands are used for depositing and `bridge withdraw-erc721` or `bridge withdraw-erc1155` are used for withdrawals.

## Preconditions
1. token pre-exists on the rootchain,
2. sender has enough balance of that token that is about to be bridged,
3. at least single validator on an Edge chain is running in a relayer mode.

## Deposit workflow
1. Deposit the tokens on the rootchain. It can be accomplished by running the following command
```bash
polygon-edge bridge deposit-erc20 \
	--sender-key <SENDER_PRIVATE_KEY> \
	--amounts <AMOUNT_IN_WEIS> \
	--receivers <RECEIVER_ADDRESS> \
	--root-token <ROOTCHAIN_ERC20_TOKEN> \
	--root-predicate <ROOT_ERC20_PREDICATE_ADDRESS> \
	--json-rpc <ROOTCHAIN_JSON_RPC_URL>
```
`ROOTCHAIN_ERC20_TOKEN`=address of an ERC20 token from a rootchain
`ROOT_ERC20_PREDICATE_ADDRESS`=`erc20PredicateAddress` from the `genesis.json`

There is an optional flag, called `minter-key` and it represents private key of account that has minter role assigned to the given ERC20 token. In case it is provided, before making deposit, token is being minted to the `sender-key` account, so that it make sure there are enough tokens to bridge.

Output of this command should be similar to this:
```bash
[DEPOSIT ERC 20]
Sender                  = 0x1FC1411A3Bd09E63d4A306FD1EB838bA457ddA13
Receivers               = 0xa0a946357221A7bf0195B0AE7dD07E2f58a3e8F6, 0xCEc294745471879704fF36C200df3737eD12633d, 0x67d61bF84a2898D98CBb4398AFddBD9E6469c67D, 0x297D8df540e3fd00148Fe83277501359A135dEA5, 0xaadac13B5eff2124Cf2d095e997F4992E1b44AB3
Amounts                 = 100, 100, 100, 100, 100
Inclusion Block Numbers = 192, 192, 192, 192, 192
Child Token Address     = 0x2f3A59d07f279Fb97feeAa7A7C1A90b6688F6dB0
```
It is important to mention that `Child Token Address` represents the address of the child token on the child chain and it is important to remember it because of withdrawal. It is going to be printed out for any token, except the native one (in case we are running a setup where the Edge chain native token is indeed some ERC20 rootchain token).

2. Wait for the bridge transaction to be settled on the child chain. After a couple of sprint blocks (sprint is equal to 5 blocks by default), bridge deposit transaction should be settled on the child chain and balances on the child token address should be updated accordingly.

The following image illustrates the deposit workflow.
![image](https://github.com/0xPolygon/polygon-edge/assets/93934272/52abfdb3-c28b-411f-9494-15dd11e39faf)

## Withdrawal workflow
1. Withdraw the tokens from the child chain is accomplished by running the following CLI command:
```bash
polygon-edge bridge withdraw-erc20 \
	--sender-key <SENDER_PRIVATE_KEY> \
	--receivers <RECEIVER_ADDRESS> \
	--amounts <AMOUNT_IN_WEIS> \
	--child-predicate 0x0000000000000000000000000000000000001004 \
	--child-token <CHILD_TOKEN_ADDRESS> \
	--json-rpc <CHILD_CHAIN_JSON_RPC_URL> \
```
Note that the `child-predicate` flag can be omitted as ChildERC20Predicate is deployed to `0x0000000000000000000000000000000000001004` by default in the genesis time.

The output of withdrawal command is as following:
```bash
[WITHDRAW ERC 20]
Sender                  = 0xa0a946357221A7bf0195B0AE7dD07E2f58a3e8F6
Receivers               = 0xa0a946357221A7bf0195B0AE7dD07E2f58a3e8F6
Amounts                 = 100
Exit Event IDs          = 6
Inclusion Block Numbers = 187
```
The most important parameter here is `Exit Event IDs`, as it is necessary for the final step, when withdrawal transaction is being finalized on a rootchain.

2. Wait for at least one epoch for checkpoint to be submitted to a rootchain. Checkpoint, among the other, contains withdrawal data. Checkpoints are regularly sent by the validators to a rootchain every 30 minutes and/or epoch-ending block.

3. Send exit transaction. It represents bridge withdrawal transaction finalization and can be accomplished by running the following CLI command
```bash
polygon-edge bridge exit \
    --sender-key <SENDER_PRIVATE_KEY> \
    --exit-helper <EXIT_HELPER> \
    --exit-id <EXIT_EVENT_ID> \
    --root-json-rpc <ROOTCHAIN_JSON_RPC_URL> \
    --child-json-rpc <CHILD_CHAIN_JSON_RPC_URL>
```
`EXIT_HELPER`=address of ExitHelper contract deployed on a rootchain. It can be found from the `exitHelperAddress` field in the `genesis.json`.
`EXIT_EVENT_ID`=id of exit event. It was the output of the `bridge withdraw-erc20` command, namely when the withdrawal was initiated on a child chain.

The following image illustrates the withdrawal workflow.
![image](https://github.com/0xPolygon/polygon-edge/assets/93934272/fc0fe473-ca61-4432-946e-1931fe6ab6e2)

**Comment by Stefan-Ethernal** [comment]
> If the token is not mapped and is made mintable, this means that there is no control over the Rootchain and whatever tokens we add in the genesis as you mentioned above, can be minted right?

Based on their origin, tokens are classified into two categories: rootchain-originated and child chain-originated ones. In case token pre-exists on the rootchain and gets bridged to the child chain, its minimal clone/copy (aka child token) is created on the child chain and gets mapped on both the rootchain and the child chain the first time such token gets deposited. Similarly goes with child chain originated tokens, with such differences that:
- minimal copy (aka child token) is created on a rootchain,
- deposit is initiated on the child chain (as bridging starts with transferring token from a child chain to a rootchain). This also means that the exit transaction is being sent right after the deposit being done (because of L2->L1 transfer),
- withdrawal is initiated on the rootchain.

> Are there any issues to this setup?

It is indeed possible to have both child chain and root chain-originated tokens on a single chain and be able to bridge them, but it is important to have in mind which root and child predicate contract addresses need to be provided to the commands and when exit commands need to be invoked.

**Comment by saurabh-lodha-16** [comment]
@Stefan-Ethernal  / @sahil3Vedi 
I tried the full flow for rootchain-originated tokens and everything works for me.

For the childchain-originated tokens, I wanted to know the commands/instructions for me to bridge the tokens.
I understand I need to deposit the tokens on child chain, but I am confused with the arguments I need to enter for root-token and root-predicate.

Also, I would need to deposit the tokens on child-chain, exit on child-chain and then withdraw on rootchain right ?

Would love to know the steps for this. Thanks

**Comment by Stefan-Ethernal** [comment]
> For the childchain-originated tokens, I wanted to know the commands/instructions for me to bridge the tokens.
I understand I need to deposit the tokens on child chain, but I am confused with the arguments I need to enter for root-token and root-predicate.

You should use the same commands as for the rootchain-originated tokens. 
The only differences are that:
1. `root-predicate` address should be `RootMintable{ERC20, ERC721, ERC1155}Predicate` address. Those contracts are deployed on the genesis, on the predefined addresses that are listed [here](https://github.com/0xPolygon/polygon-edge/blob/597a0f3d44fd21acb547f905366be8a9ee626c01/contracts/system_addresses.go#L61-L72),
2. `root-token` corresponds to the address of the child-chain-originated token that is about to be deposited,
3. the `--child-chain-mintable` flag must be provided for both deposit and withdraw commands.

Be mindful about providing JSON RPC addresses, because for the depositing L2 RPC URL needs to be provided, whereas for the withdrawal L1 RPC URL should be provided.

> Also, I would need to deposit the tokens on child-chain, exit on child-chain and then withdraw on rootchain right ?

Exactly. :100: 

A briefly description of the workflow is:
1. deposit token on the L2 (e.g. `bridge deposit-erc20` cmd)
2. wait for at least a single epoch
3. send exit transaction with appropriate exit event id (e.g. `bridge exit` cmd) -> bridge transfer is settled on the L1
4. withdraw from the L1 to the L2 (e.g. `bridge withdraw-erc20` cmd)
5. wait for it to be settled on the L2 by the relayer(s).

**Comment by saurabh-threely** [comment]
This is so wholesome.
Thanks for the detailed reply.

Will be trying it out and will let you know about it.

One last question around this.
When you say epoch, so there is a epoch size in the genesis.
So is that I have to wait for 100 blocks of that's my epoch size ?

There is less description in the docs so want to clear it out. You also mentioned 30 mins so does it correspond to the same thing ?

**Comment by saurabh-lodha-16** [comment]
This is so wholesome. @Stefan-Ethernal
Thanks for the detailed reply.

Will be trying it out and will let you know about it.
One last question around this.
When you say epoch, so there is a epoch size in the genesis.
So is that I have to wait for 100 blocks of that's my epoch size ?

There is less description in the docs so want to clear it out. You also mentioned 30 mins so does it correspond to the same thing ?

Also I have been using Polygon Mainnet as my Rootchain and the exit transaction takes a long time even when I am way past my epoch size.



The epochsize is 100 and I have been waiting for 4 hours and it still shows - 
```failed to get exit proof (exit id=1): {"code":-32603,"message":"checkpoint block not found for exit ID 1"}```

Is there a way to deug this i.e. understand which block is checkpointed or how much time it would take for the exitID to be valid. 

Thanks

**Comment by Stefan-Ethernal** [comment]
> When you say epoch, so there is a epoch size in the genesis.
So is that I have to wait for 100 blocks of that's my epoch size ?

That's right, in the `genesis.json`, there is `epochSize` (in blocks). In case there is written 100, it means that epoch lasts 100 blocks.

>  You also mentioned 30 mins so does it correspond to the same thing ?

Yes, checkpoints are being sent on every 30 minutes or on epoch-ending blocks.

> Also I have been using Polygon Mainnet as my Rootchain and the exit transaction takes a long time even when I am way past my epoch size

If that's the case, this could mean that validators do not have enough funds to cover for the transaction fees when checkpoints are being sent. You could take a look at validators output and see whether you have the similar warning log message:
`failed to submit checkpoint`.

**Comment by saurabh-lodha-16** [comment]
Thanks for responding to this. @Stefan-Ethernal 
I have checked the complete logs and I did found this issue in the 4th Validator logs.

```
2024-02-14T07:23:40.295Z [WARN]  polygon.server.polybft.checkpoint_manager: failed to submit checkpoint: checkpoint block=900 epoch number=9 error="{\"code\":-32000,\"message\":\"insufficient funds for gas * price + value: balance 59764134782235864, tx cost 82172449366474048, overshot 22408314584238184\"}"
```

- So hen you say cover the transaction fees, does this mean I have to keep the Validator funded on the Rootchain with appropriate gas ?
- What would happen if I do not maintain this amount, would there be any issue if there is no checkpointing (bridging disabled etc.)
- What is the recommended epoch size according to you ? If I keep a large epoch size number, would the checkpoint still occur in 30 mins or it would depend on the epoch size ?
- Why was this error in Validator 4 logs ? Is there any reason behind this.

Would just love to confirm the above. Thanks

**Comment by Stefan-Ethernal** [comment]
> So when you say cover the transaction fees, does this mean I have to keep the Validator funded on the Rootchain with appropriate gas?

Yes, you must ensure that your validators (or at least a single one) have enough rootchain native tokens on their balance for checkpointing to work correctly. Note that even if some validator fails to submit a checkpoint, another one (a proposer for the checkpoint block) will try to re-submit all pending ones on the next occasion.

> What would happen if I do not maintain this amount, would there be any issue if there is no checkpointing (bridging disabled etc.)

Other than bridging data from L2 to L1, the rest of the system is unaffected if checkpointing does not work.

> What is the recommended epoch size according to you?

It is part of personal preferences and use cases. You are balancing between rootchain fees and the pace at which bridge transactions are executed. We have been using epoch size=10 blocks for our testing scenarios.

>  If I keep a large epoch size number, would the checkpoint still occur in 30 mins or it would depend on the epoch size?

The checkpointing occurs every 30 mins, nevertheless epoch size.

> Why was this error in Validator 4 logs ? Is there any reason behind this.

Validator 4 was chosen to be a proposer for the given block that also needed to be checkpointed. It didn't have enough rootchain native tokens on its balance and therefore, checkpointing failed.

**Comment by saurabh-lodha-16** [comment]
Wow man. Thanks a lot for being so detailed and so clear.
Just have this last query which got lost in the middle of things.

During setting things up, we have to enable staking. This was written the integration docs - `If enable-staking flag is provided, validators will be able to continue staking on rootchain`. Does this mean that there would be continuous staking from the Validators or this means that all the new validators would need to stake ?
