### ISSUE TITLE
Spamming nodes with txs halts node consensus

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#311]
### Description

Although txpool rpc methods such as `txpool_content` no longer hang during our spam test (see steps to repro this here https://github.com/0xPolygon/polygon-sdk/issues/291), it appears that running the same test as earlier stops the targeted node's state-change cycle. When enough nodes in the validator set are targeted, new blocks are no longer able to written to the chain.

One can verify this by observing a non-incrementing block number when calling the request below:
```
{"id":1,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", true]}
```

Looking at the logs of the targeted node, one can see the `failed to broadcast, txpool is full` message and the node timing out and getting stuck in AcceptState.

I'll be sure to update this issue with any additional info I find while testing.

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon SDK `4765373 `
* branch that causes this issue `develop`

### Steps to reproduce

1. Create testnet with 4 validators and 1 non-sealing node
2. Using https://github.com/mrwillis/eth-txn-spam, run most basic type of test within that repo (mode=0 / regular transfer) with RANGE 200 and PARALLELISM 20 targeting the RPC urls of 2 validators
    1. Used AWS `c4.4xlarge` Ubuntu 20 instance in our case
3. Although txpool rpc methods no longer hang, calling `eth_getBlockByNumber(latest)` will return a stuck block number.

### Expected behaviour

Running this test shouldn't halt block writing on the targeted node and chain halt (if additional nodes are targeted).

### Actual behaviour

Running this test halts block writing on the targeted node and chain halt (if additional nodes are targeted).

**Comment by zivkovicmilos** [comment]
Hey @dankostiuk,

I ran this on the exact cluster setup you're describing and wasn't able to reproduce the problem - block production continues along normally on all nodes.

Have you been able to reproduce this with the latest `develop` version?

**Comment by zivkovicmilos** [comment]
Hey @dankostiuk,

Following up, I was able to reproduce the issue you were experiencing by running the loadbot on each node in the network against another node - the chain stopped in Accept state.

We're currently looking into it 👍 

Keeping you posted 💯

**Comment by zivkovicmilos** [comment]
Hey @dankostiuk,

Sorry for the late reply regarding this issue.

I wanted to give you more information as to what is going on and how we managed to reproduce it on our end, as well as what's being done about it.

## Reproduction

We haven't been able to reproduce following the steps you've described, but managed to see the issue during the following scenario:
* 4 node cluster (`c4.4xlarge`)
* Each node has a running stress script with 10 mnemonics
* The stress script is pointed at the next node, so Node 1 -(targets)-> Node 2 -> Node 3 -> Node 4 -> Node 1

We observed the consensus halt that you've mentioned, and identified it is caused due to a sudden buildup of transactions on the node, as well as a slowdown when processing those transactions, which cause a timeout before which someone was set to propose a block (but couldn't because they were hammered). The end result is that most nodes calculate the wrong proposer for the block, causing the consensus to halt.

## Solution

The long-term solution is to add a fail safe mechanism that resyncs the nodes on who is the proposer for the next block, if they somehow time out and land on different proposers. We've added this as a task that's gonna be tackled eventually.

The current solution, that's already live on the `develop` branch, is to significantly speed up the TxPool, which doesn't lead to the node halting with consensus since requests are handled much, _much_ quicker now.

I've tested out all of the scenarios, and the one mentioned in this reply with the new TxPool implementation, and can confirm that no such behavior was present 👍 

Please attempt to reproduce this issue with the latest pull from `develop`, and let me know if you still run into this problem 🙏

**Comment by zivkovicmilos** [comment]
Closing this issue due to  inactivity and inability to reproduce this with the latest develop branch.

I'll keep you guys posted on any related efforts in concerts to cementing the correct functioning of consensus 👍
