### ISSUE TITLE
Polygon edge POS setup scripts failing

### ISSUE THREAD

**Issue by Kvenessa** [0xPolygon/polygon-edge#489]
## Description 

We are trying to setup a standalone chain with POS consensus 

### Steps to reproduce
1. Create a network according to local setup by passing pos flag and provide accounts as premined accounts to provide funds 
2.  Clone polygon staking smart contract and run following tasks 
A. Update .env file with RPC url and account1 private key 
B.npm run stake 
C. npm run info 

Npm run info fails with error: unable to execute call: execution reverted

1. Is there a specific instructions which are missing for using pos consensus?I can see staking contract is recently updated to add validator max count which docs doesn't mention.

2. Which account private key should be provided in env file for staking? Is this a metamask account or a node key should be used? 

3. If it's node key how to get nodes private key

4. If it's metamask account then how that account proposes a block without running a node and holding a blockchain data. Will it get signing request in metamask for proposing a block?

5. What steps should be followed inorder to deploy some erc sample contract and invoke a transaction?
=>
A. Create network with genesis and premined accounts.
B. Use account x to stake the amount
This will result in account x to be selected as proposer 
C. Deploy sample erc contract with usual hardhat deploy script
D. Invoke transactions
 Is this a correct approach?

**Comment by Kourin1996** [comment]
@Kvenessa Hello, Thank you for raising the issue. 

I will answer your questions firstly.
1. As you said, we've added new CLI options for `min-validator-count` and `max-validator-count` in `genesis` command for PoS setup. But it works without these parameters. I tested right now. I didn't face such issue
2. Any account you want to make stake. Of course, this account must have enough funds to stake. To become a validator, the account must stake 1 Ether (10^18). Please use `--premine` options in `genesis` command in order to provide funds to account.
3. Validator key is in ${data_dir}/consensus/validator.key where ${data_dir} is the name you specified to run `secrets init` command
4. There is no way to propose a block from metamask. But you can send a signed transaction from metamask. If you want to use an account in metamask as a validator address, please export private key and put private key into data-dir.
5. In order to deploy contracts, you don't need additional stake because initial validators have staked in contract as default. Only when you want to add a new validator, you can stake from new account. So step B is not neccsary for deploying contract.

I found that the account had staked couldn't stake more. But I think this is not related to your issue.
Please note that initial validators have staked as default at genesis.

**Comment by Kourin1996** [comment]
@Kvenessa If you faced error when running `npm run info`, there is possibility of that Staking contract has not been deployed or using wrong contract address

**Comment by Kourin1996** [comment]
@Kvenessa There are any updates? May I ask you the following things?

* Are you using latest code of both [polygon-edge](https://github.com/0xPolygon/polygon-edge) and [staking-contracts](https://github.com/0xPolygon/staking-contracts) repository?
* Did you face this error you explained above when running `npm run info`?
* Did you set STAKING_CONTRACT_ADDRESS in .env correctly? If you setup PoS in Edge, staking contract address will be `0x0000000000000000000000000000000000001001`

**Comment by Kvenessa** [comment]
Thanks for your help @Kourin1996 , Somehow staking contract was not deployed , tried with latest polygon edge binaries and docker images we no longer see this issue in deployment now.

**Comment by Kvenessa** [comment]
> There is no way to propose a block from metamask. But you can send a signed transaction from metamask. If you want to use an account in metamask as a validator address, please export private key and put private key into data-dir.


@Kourin1996  can you please elaborate more on this if metamask account can be used doesn't this require that account to run a node in the network? I have tried POS staking with metamask account (staked 1eth with scripts provided in staking contract hardhat project) and was able to successfully deploy sample contract . Can you please provide some details how a block proposal process worked when metamask account was added as validator? 



> In order to deploy contracts, you don't need additional stake because initial validators have staked in contract as default. Only when you want to add a new validator, you can stake from new account. So step B is not neccsary for deploying contract.

Does this mean all initial nodes stake 1eth and they are selected on basis of round robin? and is there a way to configure this initial nodes staking amount?

**Comment by Kourin1996** [comment]
@Kvenessa 
> Does this mean all initial nodes stake 1eth and they are selected on basis of round robin? and is there a way to configure this initial nodes staking amount?

All initial validators specified at `genesis` command stake to staking contract as default. Which means initial validators are set to validator set in staking contract when pre-deploying this.

> can you please elaborate more on this if metamask account can be used doesn't this require that account to run a node in the network? I have tried POS staking with metamask account (staked 1eth with scripts provided in staking contract hardhat project) and was able to successfully deploy sample contract . Can you please provide some details how a block proposal process worked when metamask account was added as validator?

I'm afraid I didn't understand what you were trying to say well. But the new account will not become a validator in Edge immediately after the account stakes. Edge fetches validator set from the staking contract and updates IBFT validator set to this Every new epoch (default epoch size is 100000). Currently block producer will be chosen among validator set and changed every block production in order. (It means currently doesn't care about the stake amount) If you stake from Metamask account, you need to run a new node which uses this account's key for the validator key to become a new validator.

**Comment by zivkovicmilos** [comment]
Hey @Kvenessa,

Any updates on this issue? Are you still able to reproduce it?

**Comment by Kvenessa** [comment]
No I haven't been able to reproduce it, can confirm its working currently with latest version. Closing this issue for now.
