### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by CryptoDevving** [0xPolygon/polygon-edge#669]
Whenever I try to configure Nginx for my polygon blockchain it makes the chain unreachable.

How do I configure nginx for the Polygon Edge blockchain?

**Comment by ZeljkoBenovic** [comment]
Hi @CryptoDevving ,

I've already shared with you some tips on how to get started with Nginx [on your previous issue](https://github.com/0xPolygon/polygon-edge/issues/633#issuecomment-1195281143)

Please do keep this Issue board clean, and post issues that directly relate to the issues in `polygon-edge` code base.   
Nginx issue that you're facing, is in no way related to `polygon-edge` code base. Like I've sad before there is plenty of documentation online on how to properly configure Nginx. 

Let us know if you require some premium, paid support so that we can connect you with some of our partners.

Closing this issue for the reasons stated above.

**Comment by CryptoDevving** [comment]
@ZeljkoBenovic Where do I go to for nginx help? I am still stuck on it.
