### ISSUE TITLE
Unable to call bytecode for a deployed contract using eth_getCode

### ISSUE THREAD

**Issue by samisbakedham** [0xPolygon/polygon-edge#698]
### Description

We were trying to deploy gnosis safe's onto our polygon edge chain, Candle, and for some reason we are unable to query the bytecode for the deployments. 

### Your environment

* Ubuntu 20
* 0.5.0
* release

**Comment by laviniat1996** [comment]
Hi @samisbakedham, can you please follow [this template](https://docs.polygon.technology/docs/edge/community/report-bug) for the issue? It would help us in troubleshooting.

**Comment by laviniat1996** [comment]
Hello @samisbakedham ,

It's been quite a while since we've heard from you and we are curious if this issue still persists. We weren't able to replicate this issue on our Edgenet. We were able to call the bytecode of a token contract from the Edgenet by using this command:
```
curl https://rpc-edgenet.polygon.technology/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getCode","params":["0x8c98ea273bA22327F896Aa1a1a46E1BFf56e9b1D"],"id":1,"jsonrpc":"2.0"}'  

```
Looking forward to hearing from you!

**Comment by ivanbozic21** [comment]
Hello @samisbakedham ,

It's been quite a while since we've heard from you and we are curious if this issue still persists. We weren't able to replicate this issue on our Edgenet. We were able to call the bytecode of a token contract from the Edgenet by using this command:

curl https://rpc-edgenet.polygon.technology/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getCode","params":["0x8c98ea273bA22327F896Aa1a1a46E1BFf56e9b1D"],"id":1,"jsonrpc":"2.0"}'  

Looking forward to hearing from you!

**Comment by ivanbozic21** [comment]
@samisbakedham,

We didn't hear back from you for more than 20 days.

Please know that we will close your issue request, and you're free to raise a new one.
