### ISSUE TITLE
Submission of Vote transaction failed

### ISSUE THREAD

**Issue by avenbreaks** [0xPolygon/polygon-edge#813]
## [Subject of the issue]

I got a failure after depositing erc20 using chainbridge and cb-sol-cli, looking at transaction explorer in polygon mumbai, successful transactions still on chainbridge I received a failed transaction vote and shutting down.

### Description

```
cb-sol-cli erc20 deposit \
  --url https://polygon-mumbai.g.alchemy.com/v2/a8i3eka9XnSazezQZItazQIvQxRINb6w \
  --privateKey xxxxx \
  --gasPrice 7768432200 \
  --amount 10 \
  --dest 21 \
  --bridge "0xba341185593fbB455530d3D29f4C87f0BF4f5cad" \
  --recipient "0xD07a0990fd03757bA7cee2899735317715592b43" \
  --resourceId "32-byte resourceId"
```

`https://mumbai.polygonscan.com/tx/0xd52187b1cf6f2f92ec1ea8d13bfef551bf3f726361d582ad33cfeeb4169645dd`

### Your environment

* OS and version ( Ubuntu Pro 22 ) 
* version of the Polygon Edge ( Develop v0.6.0 )
* branch that causes this issue 

### Steps to reproduce

Follow This Step : `https://wiki.polygon.technology/docs/edge/additional-features/chainbridge/setup-erc20-transfer`

### Logs

![image](https://user-images.githubusercontent.com/93043826/196572432-edc1f065-d109-4f14-8a13-7c242529d18e.png)

**Comment by ivanbozic21** [comment]
Hi @avenbreaks 

We're reviewing your request, and we will keep you posted.

**Comment by ivanbozic21** [comment]
@avenbreaks 
After reviewing your request based on provided info, this seems to be a failure on ChainBridge side due to missing configuration.

Can you please review your setup by following the instructions once again from ChainBridge setup page:

https://wiki.polygon.technology/docs/edge/additional-features/chainbridge/setup

**Comment by ivanbozic21** [comment]
@avenbreaks
After reviewing your request based on provided info, this seems to be a failure on ChainBridge side due to missing configuration.

Can you please review your setup by following the instructions once again from ChainBridge setup page:

https://wiki.polygon.technology/docs/edge/additional-features/chainbridge/setup

**Comment by avenbreaks** [comment]
> @avenbreaks After reviewing your request based on provided info, this seems to be a failure on ChainBridge side due to missing configuration.
> 
> Can you please review your setup by following the instructions once again from ChainBridge setup page:
> 
> https://wiki.polygon.technology/docs/edge/additional-features/chainbridge/setup

Yes, I did what the document says, but I still get the same error. Is there a gas price recommendation?

**Comment by ivanbozic21** [comment]
Can you please let us know the commands that you used to configure chainbrige?
@avenbreaks

**Comment by ivanbozic21** [comment]
@avenbreaks
Can you please let us know the commands that you used to configure chainbrige?

**Comment by laviniat1996** [comment]
Hi @avenbreaks , we didn't hear from you in a while.

**Comment by avenbreaks** [comment]
Sorry late respons, i Will try again!

**Comment by laviniat1996** [comment]
Hi @avenbreaks ,

If this issue is still relevant, please let us know. Otherwise, it will be closed.
Thank you 🙏
