### ISSUE TITLE
Please Help: The block and All transaction not real-time load. need to be refresh manually. [Blockscout]

### ISSUE THREAD

**Issue by mdd0x** [0xPolygon/polygon-edge#833]
I run Polygon-Edge POS on the blockscout, once it first run , its running smoothly with realtime load for block and all transaction.
but after 10 mins its like stuck. the block and all transaction stop load. and need to refresh manually to update it.
Please Help.

This is the processing:
application=indexer fetcher=block_catchup [info] Checking if index needs to catch up in 2500ms.
application=indexer fetcher=empty_blocks_to_refetch [info] Start sanitizing of empty blocks. Batch size is 100

![image](https://user-images.githubusercontent.com/22166837/197668034-a2da6ec5-8646-420d-a3c0-001a7b85cc35.png)

And this is a latest block, 6 mins ago. it should be realtime loading second by second. so it need to be refresh (on browser) manually.
![image](https://user-images.githubusercontent.com/22166837/197668095-9b0ef888-8fbc-4b9f-ab2f-8c6669454111.png)

After refresh manually
![image](https://user-images.githubusercontent.com/22166837/197668115-dee4c6b5-4862-496d-a4c4-95bd4dead0b0.png)

Blockscout:
http://35.228.193.50:4000/

my running command:
polygon-edge server --data-dir ./data-dir --chain genesis.json  --libp2p 0.0.0.0:1478 --nat 35.198.54.39 --seal --price-limit 10000000000

**Comment by ivanbozic21** [comment]
Hi @mdd0x 

### Description

Describe your issue in as much detail as possible here

### Your setup environment

- OS and version
- The version of the Polygon Edge
- The branch that causes this issue
- Locally hosted or on the Cloud and where

### Steps to reproduce

- Tell us how to reproduce this issue <br />
- Where the issue is, if you know <br />
- Which commands triggered the issue, if any

### Is the chain producing blocks?

Please respond with Yes or No

### Expected behavior

Tell us what should happen

### Actual behavior

Tell us what happens instead

### Logs

Please upload your entire node debug logs here that demonstrate the issue if they exist.

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it
