### ISSUE TITLE
Storing slot not found on sending $ from empty account

### ISSUE THREAD

**Issue by mrwillis** [0xPolygon/polygon-edge#98]
### Description

Currently in a situation where I'm launching with dev mode (no blocks yet created), using the premine account like 

`./main dev --premine "0x...."`

I load up metamask and load up another account (NOT the premine) and try to send a balance around to any account. (You might have to manually adjust gas limit, I made https://github.com/0xPolygon/polygon-sdk/pull/97 to help) I always seem to get this error as a result from this call

https://github.com/0xPolygon/polygon-sdk/blob/develop/minimal/server.go#L243

It seems this call generates a key (the hash of the account address) that never exists in the storage.

https://github.com/0xPolygon/polygon-sdk/blob/develop/minimal/server.go#L229

Some debug output

![image](https://user-images.githubusercontent.com/2652683/126831334-bca99ebd-22d2-4412-8465-dd22f22493c1.png)

### Your environment

* OS and version Ubuntu 20
* version of the Polygon SDK  2f50a194f21d972b542ccd1e1571ccba40c5c810
* branch that causes this issue develop

### Steps to reproduce

* Tell us how to reproduce this issue
1. Set premine to account 1, start up the chain. Load up metamask targeting account 1.
2. Set premine to account 2, start up the chain. Load up metamask still targeting account 1.
3. Try to send $ from account 1 to any account 

* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Logs

Please paste any logs here that demonstrate the issue, if they exist

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

**Comment by lazartravica** [comment]
@mrwillis This is expected behaviour of the log output of the polygon-sdk node if you try to send funds from an address that hasn't had any transactions to it and is not premined.

Yet, to be double sure that I understand what the issue is, can you tell me in the `Steps to reproduce` section why do you start up the chain setting different premines each time?

An important thing to note (since you are mentioning running the dev command subsequently with a different premine argument) is that the `dev` command doesn't re-generate `genesis.json` if it already finds it on the filesystem, that is why without deleting the data-dir and the genesis file in between changing the `--premine` parameter for the dev command the new premines will not take effect as it will read from the old data-dir  (`test-chain/`) and `genesis.json`.

**Comment by mrwillis** [comment]
@lazartravica yep got that part. The reason why I do a different pre-mine is so metamask will incorrectly show the balance as metamask doesn't refetch the balance that often it seems. It's kind of just a hack to be able to execute the transaction via metamask (which is supposed to fail). So even when I change the premine to account 2, metamask still shows account 1 has a balance (even though it doesn't). 

If anything this is more of a JSON-RPC error I feel? The spec does not indicate what should happen here if the transaction cannot be submitted.

https://eth.wiki/json-rpc/API#eth_sendrawtransaction
